db:
  image: "mariadb:%%config.mariadb.version:-latest%%"
  environment:
    MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
    MARIADB_DATABASE: "${DB_DATABASE}"
    MARIADB_USER: "${DB_USERNAME}"
    MARIADB_PASSWORD: "${DB_PASSWORD}"
    MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
  volumes:
    - db_data:/var/lib/mysql
  ports:
    - "%%config.mariadb.port:-3306%%:3306"
  networks:
    - frank
  healthcheck:
    test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
    interval: 5s
    timeout: 3s
    retries: 10
