package compose

import (
	"os"
	"strings"
	"testing"

	"github.com/phlisg/frank-cli/internal/config"
	"github.com/phlisg/frank-cli/internal/template"
)

func newTestGenerator(t *testing.T) *Generator {
	t.Helper()
	engine := template.New(os.DirFS("../.."))
	return New(engine)
}

func TestGenerate_FrankenPHPWithPgsql(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Laravel:  config.Laravel{Version: "latest"},
		Services: []string{"pgsql", "mailpit"},
	}

	out, err := g.Generate(cfg, "myapp")
	if err != nil {
		t.Fatalf("Generate error: %v", err)
	}

	checks := []string{
		"# Generated by Frank",
		"laravel.test:",
		"pgsql:",
		"mailpit:",
		"networks:",
		"frank:",
		"driver: bridge",
		"pgsql_data:",
	}
	for _, want := range checks {
		if !strings.Contains(out, want) {
			t.Errorf("expected %q in output:\n%s", want, out)
		}
	}
}

func TestGenerate_FPMWithMySQL(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.3", Runtime: "fpm"},
		Services: []string{"mysql", "redis"},
	}

	out, err := g.Generate(cfg, "testapp")
	if err != nil {
		t.Fatalf("Generate error: %v", err)
	}

	if !strings.Contains(out, "laravel.test:") {
		t.Error("expected laravel.test service")
	}
	if !strings.Contains(out, "nginx:") {
		t.Error("expected nginx service for fpm runtime")
	}
	if !strings.Contains(out, "mysql:") {
		t.Error("expected mysql service")
	}
	if !strings.Contains(out, "redis:") {
		t.Error("expected redis service")
	}
	if !strings.Contains(out, "mysql_data:") {
		t.Error("expected mysql_data volume")
	}
	if !strings.Contains(out, "redis_data:") {
		t.Error("expected redis_data volume")
	}
}

func TestGenerate_SQLiteNoComposeFragment(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Services: []string{"sqlite"},
	}

	out, err := g.Generate(cfg, "myapp")
	if err != nil {
		t.Fatalf("Generate error: %v", err)
	}
	// sqlite should not appear as a service
	if strings.Contains(out, "sqlite:") {
		t.Error("sqlite should not appear as a compose service")
	}
}

func TestGenerate_NoVolumesWhenNoneNeeded(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Services: []string{"mailpit", "memcached"},
	}

	out, err := g.Generate(cfg, "myapp")
	if err != nil {
		t.Fatalf("Generate error: %v", err)
	}
	// Neither mailpit nor memcached needs a named volume
	if strings.Contains(out, "mailpit_data") || strings.Contains(out, "memcached_data") {
		t.Error("unexpected volume entries for services that don't need them")
	}
}

func TestGenerate_NetworkIsFrank(t *testing.T) {
	g := newTestGenerator(t)
	cfg := config.New()

	out, err := g.Generate(cfg, "myapp")
	if err != nil {
		t.Fatalf("Generate error: %v", err)
	}
	if !strings.Contains(out, "frank:") {
		t.Error("expected frank network")
	}
	if strings.Contains(out, "sail:") {
		t.Error("unexpected sail network — should be frank")
	}
}

func TestGenerate_HeaderComment(t *testing.T) {
	g := newTestGenerator(t)
	cfg := config.New()

	out, err := g.Generate(cfg, "myapp")
	if err != nil {
		t.Fatalf("Generate error: %v", err)
	}
	if !strings.HasPrefix(out, "# Generated by Frank") {
		t.Error("compose.yaml should start with the generated-by header")
	}
}

func TestWrite_CreatesFile(t *testing.T) {
	g := newTestGenerator(t)
	cfg := config.New()
	dir := t.TempDir()

	if err := g.Write(cfg, "myapp", dir); err != nil {
		t.Fatalf("Write error: %v", err)
	}

	data, err := os.ReadFile(dir + "/compose.yaml")
	if err != nil {
		t.Fatalf("compose.yaml not created: %v", err)
	}
	if !strings.Contains(string(data), "laravel.test:") {
		t.Error("expected laravel.test in written compose.yaml")
	}
}

func TestHostPortKey(t *testing.T) {
	cases := []struct {
		in   string
		want string
	}{
		{"5432:5432", "5432/tcp"},
		{"443:443/udp", "443/udp"},
		{"80:80", "80/tcp"},
		{"1025:1025", "1025/tcp"},
	}
	for _, c := range cases {
		got := hostPortKey(c.in)
		if got != c.want {
			t.Errorf("hostPortKey(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestValidatePorts_Conflict(t *testing.T) {
	services := map[string]interface{}{
		"svc1": map[string]interface{}{
			"ports": []interface{}{"5432:5432"},
		},
		"svc2": map[string]interface{}{
			"ports": []interface{}{"5432:3306"},
		},
	}
	if err := validatePorts(services); err == nil {
		t.Error("expected port conflict error")
	}
}

func TestValidatePorts_TCPUDPNoConflict(t *testing.T) {
	// TCP and UDP on same port should not conflict
	services := map[string]interface{}{
		"app": map[string]interface{}{
			"ports": []interface{}{"443:443", "443:443/udp"},
		},
	}
	if err := validatePorts(services); err != nil {
		t.Errorf("TCP and UDP on same port should not conflict: %v", err)
	}
}
