package compose

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/phlisg/frank/internal/config"
	"github.com/phlisg/frank/internal/template"
)

const header = "# Generated by Frank — edit frank.yaml, not this file\n\n"

// volumeServices maps service name → named volume it requires.
var volumeServices = map[string]string{
	"pgsql":       "pgsql_data",
	"mysql":       "mysql_data",
	"mariadb":     "mariadb_data",
	"redis":       "redis_data",
	"meilisearch": "meilisearch_data",
}

// Generator builds compose.yaml from a Config using the template Engine.
type Generator struct {
	engine *template.Engine
}

// New creates a Generator backed by the given template Engine.
func New(engine *template.Engine) *Generator {
	return &Generator{engine: engine}
}

// Generate produces a compose.yaml string for the given config and project name.
func (g *Generator) Generate(cfg *config.Config, projectName string) (string, error) {
	services := map[string]interface{}{}
	volumes := map[string]interface{}{}

	// 1. Render and merge runtime compose fragment.
	runtimeFrag, err := g.engine.RenderRuntime(cfg.PHP.Runtime, "compose.fragment.tmpl", template.Data{
		PHPVersion: cfg.PHP.Version,
	})
	if err != nil {
		return "", fmt.Errorf("runtime fragment: %w", err)
	}
	if err := mergeFragment(services, runtimeFrag); err != nil {
		return "", fmt.Errorf("merge runtime fragment: %w", err)
	}

	// 2. Render and merge each service compose fragment.
	for _, svc := range cfg.Services {
		if svc == "sqlite" {
			continue // sqlite has no compose fragment
		}
		svcCfg := cfg.Config[svc]
		frag, err := g.engine.RenderServiceCompose(svc, svcCfg, projectName)
		if err != nil {
			return "", fmt.Errorf("service %q fragment: %w", svc, err)
		}
		if err := mergeFragment(services, frag); err != nil {
			return "", fmt.Errorf("merge service %q fragment: %w", svc, err)
		}
		if vol, ok := volumeServices[svc]; ok {
			volumes[vol] = map[string]interface{}{"driver": "local"}
		}
	}

	// 3. Validate host port uniqueness.
	if err := validatePorts(services); err != nil {
		return "", err
	}

	// 4. Assemble final structure.
	compose := map[string]interface{}{
		"services": services,
		"networks": map[string]interface{}{
			"frank": map[string]interface{}{
				"driver": "bridge",
			},
		},
	}
	if len(volumes) > 0 {
		compose["volumes"] = volumes
	}

	out, err := yaml.Marshal(compose)
	if err != nil {
		return "", fmt.Errorf("marshal compose.yaml: %w", err)
	}

	return header + string(out), nil
}

// Write generates compose.yaml and writes it to dir.
func (g *Generator) Write(cfg *config.Config, projectName, dir string) error {
	content, err := g.Generate(cfg, projectName)
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "compose.yaml"), []byte(content), 0644)
}

// mergeFragment parses a YAML service fragment and merges it into services.
// Each fragment is a map of service-name → service-definition.
func mergeFragment(services map[string]interface{}, fragment string) error {
	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(fragment), &parsed); err != nil {
		return fmt.Errorf("parse fragment YAML: %w", err)
	}
	for name, def := range parsed {
		services[name] = def
	}
	return nil
}

// validatePorts checks that no two services bind the same host port + protocol.
func validatePorts(services map[string]interface{}) error {
	seen := map[string]string{} // "port/proto" → service name
	for svcName, svcDef := range services {
		svcMap, ok := svcDef.(map[string]interface{})
		if !ok {
			continue
		}
		ports, ok := svcMap["ports"].([]interface{})
		if !ok {
			continue
		}
		for _, portEntry := range ports {
			portStr, ok := portEntry.(string)
			if !ok {
				continue
			}
			key := hostPortKey(portStr)
			if prev, conflict := seen[key]; conflict {
				return fmt.Errorf("port conflict on %s: services %q and %q both bind the same host port", key, prev, svcName)
			}
			seen[key] = svcName
		}
	}
	return nil
}

// hostPortKey returns "hostPort/proto" for a Docker port mapping string.
// e.g. "5432:5432" → "5432/tcp", "443:443/udp" → "443/udp"
func hostPortKey(mapping string) string {
	proto := "tcp"
	if idx := strings.Index(mapping, "/"); idx != -1 {
		proto = mapping[idx+1:]
		mapping = mapping[:idx]
	}
	host := strings.SplitN(mapping, ":", 2)[0]
	return host + "/" + proto
}
