package compose

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/phlisg/frank/internal/config"
	"github.com/phlisg/frank/internal/template"
)

const header = "# Generated by Frank — edit frank.yaml, not this file\n\n"

// healthcheckedServices is the set of services that expose a Docker healthcheck.
// These use condition: service_healthy in depends_on; others use service_started.
var healthcheckedServices = map[string]bool{
	"pgsql": true, "mysql": true, "mariadb": true,
	"redis": true, "meilisearch": true, "mailpit": true,
}

// volumeServices maps service name → named volume it requires.
var volumeServices = map[string]string{
	"pgsql":       "pgsql_data",
	"mysql":       "mysql_data",
	"mariadb":     "mariadb_data",
	"redis":       "redis_data",
	"meilisearch": "meilisearch_data",
}

// Generator builds compose.yaml from a Config using the template Engine.
type Generator struct {
	engine *template.Engine
}

// New creates a Generator backed by the given template Engine.
func New(engine *template.Engine) *Generator {
	return &Generator{engine: engine}
}

// Generate produces a compose.yaml string for the given config and project name.
func (g *Generator) Generate(cfg *config.Config, projectName string) (string, error) {
	services := map[string]interface{}{}
	volumes := map[string]interface{}{}

	// 1. Render and merge runtime compose fragment.
	runtimeFrag, err := g.engine.RenderRuntime(cfg.PHP.Runtime, "compose.fragment.tmpl", template.Data{
		PHPVersion: cfg.PHP.Version,
	})
	if err != nil {
		return "", fmt.Errorf("runtime fragment: %w", err)
	}
	if err := mergeFragment(services, runtimeFrag); err != nil {
		return "", fmt.Errorf("merge runtime fragment: %w", err)
	}

	// 2. Render and merge each service compose fragment.
	for _, svc := range cfg.Services {
		if svc == "sqlite" {
			continue // sqlite has no compose fragment
		}
		svcCfg := cfg.Config[svc]
		frag, err := g.engine.RenderServiceCompose(svc, svcCfg, projectName)
		if err != nil {
			return "", fmt.Errorf("service %q fragment: %w", svc, err)
		}
		if err := mergeFragment(services, frag); err != nil {
			return "", fmt.Errorf("merge service %q fragment: %w", svc, err)
		}
		if vol, ok := volumeServices[svc]; ok {
			volumes[vol] = map[string]interface{}{"driver": "local"}
		}
	}

	// 3. Inject depends_on into laravel.test based on which services are present.
	//    Done post-merge because templates don't know which services were selected.
	deps := map[string]interface{}{}
	for _, svc := range cfg.Services {
		if svc == "sqlite" {
			continue // sqlite has no compose service
		}
		condition := "service_started"
		if healthcheckedServices[svc] {
			condition = "service_healthy"
		}
		deps[svc] = map[string]interface{}{"condition": condition}
	}
	if len(deps) > 0 {
		if lt, ok := services["laravel.test"].(map[string]interface{}); ok {
			lt["depends_on"] = deps
		}
	}

	// 4. Emit declared worker services (schedule + queue pools).
	if err := g.emitWorkers(services, cfg, projectName); err != nil {
		return "", err
	}

	// 5. Validate host port uniqueness.
	if err := validatePorts(services); err != nil {
		return "", err
	}

	// 6. Assemble final structure.
	compose := map[string]interface{}{
		"services": services,
		"networks": map[string]interface{}{
			"frank": map[string]interface{}{
				"driver": "bridge",
			},
		},
	}
	if len(volumes) > 0 {
		compose["volumes"] = volumes
	}

	out, err := yaml.Marshal(compose)
	if err != nil {
		return "", fmt.Errorf("marshal compose.yaml: %w", err)
	}

	return header + string(out), nil
}

// Write generates compose.yaml and writes it to .frank/ inside dir.
func (g *Generator) Write(cfg *config.Config, projectName, dir string) error {
	content, err := g.Generate(cfg, projectName)
	if err != nil {
		return err
	}
	frankDir := filepath.Join(dir, ".frank")
	if err := os.MkdirAll(frankDir, 0755); err != nil {
		return fmt.Errorf("create .frank directory: %w", err)
	}
	return os.WriteFile(filepath.Join(frankDir, "compose.yaml"), []byte(content), 0644)
}

// emitWorkers renders and merges declared worker services (schedule + queue
// pools) into the services map. When cfg.PHP.Runtime == "fpm", it also injects
// `user: sail` on every declared worker so CLI commands drop root before
// touching the bind mount (php-fpm's in-pool user drop doesn't apply to CLI).
//
// Keep worker fragment templates runtime-agnostic; the runtime coupling lives
// here, parallel to the depends_on injection in Generate().
func (g *Generator) emitWorkers(services map[string]interface{}, cfg *config.Config, projectName string) error {
	w := cfg.Workers
	if !w.Schedule && len(w.Queue) == 0 {
		return nil
	}

	isFPM := cfg.PHP.Runtime == "fpm"

	if w.Schedule {
		frag, err := g.engine.RenderWorker("schedule", template.WorkerData{
			ProjectName: projectName,
		})
		if err != nil {
			return fmt.Errorf("schedule worker fragment: %w", err)
		}
		if err := mergeFragment(services, frag); err != nil {
			return fmt.Errorf("merge schedule worker fragment: %w", err)
		}
		if isFPM {
			injectSailUser(services, "laravel.schedule")
		}
	}

	for _, pool := range w.Queue {
		queuesCSV := strings.Join(pool.Queues, ",")
		for i := 1; i <= pool.Count; i++ {
			name := fmt.Sprintf("laravel.queue.%s.%d", pool.Name, i)
			frag, err := g.engine.RenderWorker("queue", template.WorkerData{
				ProjectName: projectName,
				ServiceName: name,
				PoolName:    pool.Name,
				QueuesCSV:   queuesCSV,
				Tries:       pool.Tries,
				Timeout:     pool.Timeout,
				Memory:      pool.Memory,
				Sleep:       pool.Sleep,
				Backoff:     pool.Backoff,
			})
			if err != nil {
				return fmt.Errorf("queue worker fragment %q: %w", name, err)
			}
			if err := mergeFragment(services, frag); err != nil {
				return fmt.Errorf("merge queue worker fragment %q: %w", name, err)
			}
			if isFPM {
				injectSailUser(services, name)
			}
		}
	}

	return nil
}

// injectSailUser sets `user: sail` on the named service if it is a declared
// worker (label frank.worker == "declared"). No-op if the service is missing
// or not a declared worker.
func injectSailUser(services map[string]interface{}, name string) {
	svc, ok := services[name].(map[string]interface{})
	if !ok {
		return
	}
	labels, ok := svc["labels"].(map[string]interface{})
	if !ok {
		return
	}
	if labels["frank.worker"] != "declared" {
		return
	}
	svc["user"] = "sail"
}

// mergeFragment parses a YAML service fragment and merges it into services.
// Each fragment is a map of service-name → service-definition.
func mergeFragment(services map[string]interface{}, fragment string) error {
	var parsed map[string]interface{}
	if err := yaml.Unmarshal([]byte(fragment), &parsed); err != nil {
		return fmt.Errorf("parse fragment YAML: %w", err)
	}
	for name, def := range parsed {
		services[name] = def
	}
	return nil
}

// validatePorts checks that no two services bind the same host port + protocol.
func validatePorts(services map[string]interface{}) error {
	seen := map[string]string{} // "port/proto" → service name
	for svcName, svcDef := range services {
		svcMap, ok := svcDef.(map[string]interface{})
		if !ok {
			continue
		}
		ports, ok := svcMap["ports"].([]interface{})
		if !ok {
			continue
		}
		for _, portEntry := range ports {
			portStr, ok := portEntry.(string)
			if !ok {
				continue
			}
			key := hostPortKey(portStr)
			if prev, conflict := seen[key]; conflict {
				return fmt.Errorf("port conflict on %s: services %q and %q both bind the same host port", key, prev, svcName)
			}
			seen[key] = svcName
		}
	}
	return nil
}

// hostPortKey returns "hostPort/proto" for a Docker port mapping string.
// e.g. "5432:5432" → "5432/tcp", "443:443/udp" → "443/udp"
func hostPortKey(mapping string) string {
	proto := "tcp"
	if idx := strings.Index(mapping, "/"); idx != -1 {
		proto = mapping[idx+1:]
		mapping = mapping[:idx]
	}
	host := strings.SplitN(mapping, ":", 2)[0]
	return host + "/" + proto
}
