package compose

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/phlisg/frank/internal/config"
	"github.com/phlisg/frank/internal/template"
)

func newTestGenerator(t *testing.T) *Generator {
	t.Helper()
	engine := template.New(os.DirFS("../.."))
	return New(engine)
}

func TestGenerate_FrankenPHPWithPgsql(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Laravel:  config.Laravel{Version: "latest"},
		Services: []string{"pgsql", "mailpit"},
	}

	out, err := g.Generate(cfg, "myapp")
	if err != nil {
		t.Fatalf("Generate error: %v", err)
	}

	checks := []string{
		"# Generated by Frank",
		"laravel.test:",
		"pgsql:",
		"mailpit:",
		"networks:",
		"frank:",
		"driver: bridge",
		"pgsql_data:",
	}
	for _, want := range checks {
		if !strings.Contains(out, want) {
			t.Errorf("expected %q in output:\n%s", want, out)
		}
	}
}

func TestGenerate_FPMWithMySQL(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.3", Runtime: "fpm"},
		Services: []string{"mysql", "redis"},
	}

	out, err := g.Generate(cfg, "testapp")
	if err != nil {
		t.Fatalf("Generate error: %v", err)
	}

	if !strings.Contains(out, "laravel.test:") {
		t.Error("expected laravel.test service")
	}
	if !strings.Contains(out, "nginx:") {
		t.Error("expected nginx service for fpm runtime")
	}
	if !strings.Contains(out, "mysql:") {
		t.Error("expected mysql service")
	}
	if !strings.Contains(out, "redis:") {
		t.Error("expected redis service")
	}
	if !strings.Contains(out, "mysql_data:") {
		t.Error("expected mysql_data volume")
	}
	if !strings.Contains(out, "redis_data:") {
		t.Error("expected redis_data volume")
	}
}

func TestGenerate_SQLiteNoComposeFragment(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Services: []string{"sqlite"},
	}

	out, err := g.Generate(cfg, "myapp")
	if err != nil {
		t.Fatalf("Generate error: %v", err)
	}
	// sqlite should not appear as a service
	if strings.Contains(out, "sqlite:") {
		t.Error("sqlite should not appear as a compose service")
	}
}

func TestGenerate_NoVolumesWhenNoneNeeded(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Services: []string{"mailpit", "memcached"},
	}

	out, err := g.Generate(cfg, "myapp")
	if err != nil {
		t.Fatalf("Generate error: %v", err)
	}
	// Neither mailpit nor memcached needs a named volume
	if strings.Contains(out, "mailpit_data") || strings.Contains(out, "memcached_data") {
		t.Error("unexpected volume entries for services that don't need them")
	}
}

func TestGenerate_NetworkIsFrank(t *testing.T) {
	g := newTestGenerator(t)
	cfg := config.New()

	out, err := g.Generate(cfg, "myapp")
	if err != nil {
		t.Fatalf("Generate error: %v", err)
	}
	if !strings.Contains(out, "frank:") {
		t.Error("expected frank network")
	}
	if strings.Contains(out, "sail:") {
		t.Error("unexpected sail network — should be frank")
	}
}

func TestGenerate_HeaderComment(t *testing.T) {
	g := newTestGenerator(t)
	cfg := config.New()

	out, err := g.Generate(cfg, "myapp")
	if err != nil {
		t.Fatalf("Generate error: %v", err)
	}
	if !strings.HasPrefix(out, "# Generated by Frank") {
		t.Error("compose.yaml should start with the generated-by header")
	}
}

func TestWrite_CreatesFile(t *testing.T) {
	g := newTestGenerator(t)
	cfg := config.New()
	dir := t.TempDir()

	// Write() expects .frank/ to already exist (created by generate()).
	if err := os.MkdirAll(filepath.Join(dir, ".frank"), 0755); err != nil {
		t.Fatalf("mkdir .frank: %v", err)
	}

	if err := g.Write(cfg, "myapp", dir); err != nil {
		t.Fatalf("Write error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, ".frank", "compose.yaml"))
	if err != nil {
		t.Fatalf(".frank/compose.yaml not created: %v", err)
	}
	if !strings.Contains(string(data), "laravel.test:") {
		t.Error("expected laravel.test in written compose.yaml")
	}
}

func TestHostPortKey(t *testing.T) {
	cases := []struct {
		in   string
		want string
	}{
		{"5432:5432", "5432/tcp"},
		{"443:443/udp", "443/udp"},
		{"80:80", "80/tcp"},
		{"1025:1025", "1025/tcp"},
	}
	for _, c := range cases {
		got := hostPortKey(c.in)
		if got != c.want {
			t.Errorf("hostPortKey(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestValidatePorts_Conflict(t *testing.T) {
	services := map[string]interface{}{
		"svc1": map[string]interface{}{
			"ports": []interface{}{"5432:5432"},
		},
		"svc2": map[string]interface{}{
			"ports": []interface{}{"5432:3306"},
		},
	}
	if err := validatePorts(services); err == nil {
		t.Error("expected port conflict error")
	}
}

func TestGenerate_NoWorkers_Unchanged(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Laravel:  config.Laravel{Version: "latest"},
		Services: []string{"pgsql", "mailpit"},
	}
	out, err := g.Generate(cfg, "myapp")
	if err != nil {
		t.Fatalf("Generate error: %v", err)
	}
	if strings.Contains(out, "laravel.schedule") {
		t.Error("no schedule worker expected when Workers.Schedule == false")
	}
	if strings.Contains(out, "laravel.queue.") {
		t.Error("no queue workers expected when Workers.Queue is empty")
	}
}

func TestGenerate_ScheduleOnly(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Laravel:  config.Laravel{Version: "latest"},
		Services: []string{"pgsql"},
		Workers:  config.Workers{Schedule: true},
	}
	out, err := g.Generate(cfg, "myapp")
	if err != nil {
		t.Fatalf("Generate error: %v", err)
	}
	checks := []string{
		"laravel.schedule:",
		"frank-myapp-laravel.test",
		"frank.worker: declared",
		"frank.worker.type: schedule",
		"schedule:work",
		"unless-stopped",
	}
	for _, want := range checks {
		if !strings.Contains(out, want) {
			t.Errorf("expected %q in output:\n%s", want, out)
		}
	}
	if strings.Contains(out, "laravel.queue.") {
		t.Error("unexpected queue worker when only schedule enabled")
	}
}

func TestGenerate_QueuePoolCountThree(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Laravel:  config.Laravel{Version: "latest"},
		Services: []string{"pgsql"},
		Workers: config.Workers{
			Queue: []config.QueuePool{
				{Name: "default", Queues: []string{"default"}, Count: 3},
			},
		},
	}
	out, err := g.Generate(cfg, "myapp")
	if err != nil {
		t.Fatalf("Generate error: %v", err)
	}
	for _, name := range []string{"laravel.queue.default.1:", "laravel.queue.default.2:", "laravel.queue.default.3:"} {
		if !strings.Contains(out, name) {
			t.Errorf("expected %q in output:\n%s", name, out)
		}
	}
	if strings.Contains(out, "laravel.queue.default.4") {
		t.Error("unexpected 4th queue worker for count=3")
	}
	if !strings.Contains(out, "frank.worker.pool: default") {
		t.Error("expected pool label")
	}
	if !strings.Contains(out, "--queue=default") {
		t.Error("expected --queue=default flag in command")
	}
}

func TestGenerate_MultiplePoolsNamed(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Laravel:  config.Laravel{Version: "latest"},
		Services: []string{"pgsql"},
		Workers: config.Workers{
			Queue: []config.QueuePool{
				{Name: "high", Queues: []string{"high", "critical"}, Count: 2},
				{Name: "default", Queues: []string{"default"}, Count: 1},
			},
		},
	}
	out, err := g.Generate(cfg, "myapp")
	if err != nil {
		t.Fatalf("Generate error: %v", err)
	}
	for _, name := range []string{
		"laravel.queue.high.1:",
		"laravel.queue.high.2:",
		"laravel.queue.default.1:",
	} {
		if !strings.Contains(out, name) {
			t.Errorf("expected %q in output:\n%s", name, out)
		}
	}
	if strings.Contains(out, "laravel.queue.high.3") {
		t.Error("unexpected 3rd high worker for count=2")
	}
	if strings.Contains(out, "laravel.queue.default.2") {
		t.Error("unexpected 2nd default worker for count=1")
	}
	if !strings.Contains(out, "--queue=high,critical") {
		t.Error("expected CSV queue list for pool with multiple queues")
	}
}

func TestGenerate_FrankenPHPWorkersNoUserKey(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Laravel:  config.Laravel{Version: "latest"},
		Services: []string{"pgsql"},
		Workers: config.Workers{
			Schedule: true,
			Queue:    []config.QueuePool{{Name: "default", Queues: []string{"default"}, Count: 1}},
		},
	}
	out, err := g.Generate(cfg, "myapp")
	if err != nil {
		t.Fatalf("Generate error: %v", err)
	}
	// frankenphp entrypoint does the gosu drop — no user: on workers.
	if strings.Contains(out, "user: sail") {
		t.Error("frankenphp runtime must not inject user: sail on workers")
	}
}

func TestGenerate_FPMWorkersNoSailUser(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.4", Runtime: "fpm"},
		Services: []string{"mysql"},
		Workers: config.Workers{
			Schedule: true,
			Queue:    []config.QueuePool{{Name: "default", Queues: []string{"default"}, Count: 2}},
		},
	}
	out, err := g.Generate(cfg, "myapp")
	if err != nil {
		t.Fatalf("Generate error: %v", err)
	}
	// user: sail is no longer injected in compose — the image entrypoint
	// handles UID remap + gosu drop for non-fpm commands.
	n := strings.Count(out, "user: sail")
	if n != 0 {
		t.Errorf("expected 0 occurrences of 'user: sail', got %d in:\n%s", n, out)
	}
}

func TestGenerate_QueuePassthroughFlags(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Laravel:  config.Laravel{Version: "latest"},
		Services: []string{"pgsql"},
		Workers: config.Workers{
			Queue: []config.QueuePool{
				{
					Name: "default", Queues: []string{"default"}, Count: 1,
					Tries: 3, Timeout: 60, Memory: 128, Sleep: 5, Backoff: 2,
				},
			},
		},
	}
	out, err := g.Generate(cfg, "myapp")
	if err != nil {
		t.Fatalf("Generate error: %v", err)
	}
	for _, flag := range []string{"--tries=3", "--timeout=60", "--memory=128", "--sleep=5", "--backoff=2"} {
		if !strings.Contains(out, flag) {
			t.Errorf("expected passthrough flag %q in:\n%s", flag, out)
		}
	}
}

func TestGenerate_QueuePassthroughOmittedWhenZero(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Laravel:  config.Laravel{Version: "latest"},
		Services: []string{"pgsql"},
		Workers: config.Workers{
			Queue: []config.QueuePool{
				{Name: "default", Queues: []string{"default"}, Count: 1},
			},
		},
	}
	out, err := g.Generate(cfg, "myapp")
	if err != nil {
		t.Fatalf("Generate error: %v", err)
	}
	for _, flag := range []string{"--tries=", "--timeout=", "--memory=", "--sleep=", "--backoff="} {
		if strings.Contains(out, flag) {
			t.Errorf("unexpected passthrough flag %q with zero value in:\n%s", flag, out)
		}
	}
}

func TestValidatePorts_TCPUDPNoConflict(t *testing.T) {
	// TCP and UDP on same port should not conflict
	services := map[string]interface{}{
		"app": map[string]interface{}{
			"ports": []interface{}{"443:443", "443:443/udp"},
		},
	}
	if err := validatePorts(services); err != nil {
		t.Errorf("TCP and UDP on same port should not conflict: %v", err)
	}
}
