package compose

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/phlisg/frank-cli/internal/config"
)

// envLine is a single line in a .env file — either a KEY=VALUE pair or a comment/blank.
type envLine struct {
	comment bool
	key     string
	value   string
}

func comment(text string) envLine { return envLine{comment: true, value: text} }
func blank() envLine              { return envLine{comment: true, value: ""} }
func kv(key, value string) envLine {
	return envLine{key: key, value: value}
}

// envHeader is the standard generated-by comment.
const envHeader = "# Generated by Frank — edit frank.yaml, not this file"

// baseEnvLines returns the Laravel base environment variables.
func baseEnvLines(projectName string) []envLine {
	return []envLine{
		comment(envHeader),
		blank(),
		comment("# Application"),
		kv("APP_NAME", projectName),
		kv("APP_ENV", "local"),
		kv("APP_KEY", ""),
		kv("APP_DEBUG", "true"),
		kv("APP_URL", "http://localhost"),
		blank(),
		comment("# Logging"),
		kv("LOG_CHANNEL", "stack"),
		kv("LOG_DEPRECATIONS_CHANNEL", "null"),
		kv("LOG_LEVEL", "debug"),
		blank(),
		comment("# Database — overridden below by configured service"),
		kv("DB_CONNECTION", "sqlite"),
		blank(),
		comment("# Cache / Session / Queue — overridden below by redis/memcached"),
		kv("BROADCAST_DRIVER", "log"),
		kv("CACHE_STORE", "file"),
		kv("FILESYSTEM_DISK", "local"),
		kv("QUEUE_CONNECTION", "sync"),
		kv("SESSION_DRIVER", "file"),
		kv("SESSION_LIFETIME", "120"),
		blank(),
		comment("# Search — overridden below by meilisearch"),
		kv("SCOUT_DRIVER", "collection"),
		blank(),
		comment("# Mail — overridden below by mailpit"),
		kv("MAIL_MAILER", "log"),
		kv("MAIL_HOST", "127.0.0.1"),
		kv("MAIL_PORT", "2525"),
		kv("MAIL_USERNAME", "null"),
		kv("MAIL_PASSWORD", "null"),
		kv("MAIL_ENCRYPTION", "null"),
		kv("MAIL_FROM_ADDRESS", fmt.Sprintf("\"hello@example.com\"")),
		kv("MAIL_FROM_NAME", fmt.Sprintf("\"${APP_NAME}\"")),
		blank(),
		comment("# Vite"),
		kv("VITE_APP_NAME", "${APP_NAME}"),
		blank(),
		comment("# Development tools"),
		kv("PSYSH_HOME", "/tmp"),
	}
}

// GenerateEnv produces a .env string for the given config and project name.
func (g *Generator) GenerateEnv(cfg *config.Config, projectName string) (string, error) {
	return g.buildEnv(cfg, projectName, false)
}

// GenerateEnvExample produces a .env.example string with placeholder values.
func (g *Generator) GenerateEnvExample(cfg *config.Config, projectName string) (string, error) {
	return g.buildEnv(cfg, projectName, true)
}

// WriteEnv generates .env and .env.example and writes both to dir.
func (g *Generator) WriteEnv(cfg *config.Config, projectName, dir string) error {
	env, err := g.GenerateEnv(cfg, projectName)
	if err != nil {
		return err
	}
	example, err := g.GenerateEnvExample(cfg, projectName)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, ".env"), []byte(env), 0644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, ".env.example"), []byte(example), 0644)
}

func (g *Generator) buildEnv(cfg *config.Config, projectName string, isExample bool) (string, error) {
	lines := baseEnvLines(projectName)

	for _, svc := range cfg.Services {
		svcCfg := cfg.Config[svc]
		rendered, err := g.engine.RenderServiceEnv(svc, svcCfg, projectName)
		if err != nil {
			return "", fmt.Errorf("service %q env: %w", svc, err)
		}

		// Parse the rendered block into key=value pairs and append as an
		// overriding section after the base vars.
		block, err := parseEnvBlock(rendered)
		if err != nil {
			return "", fmt.Errorf("parse service %q env block: %w", svc, err)
		}

		lines = append(lines, blank(), comment(fmt.Sprintf("# %s", svc)))
		for _, line := range block {
			lines = append(lines, line)
		}
	}

	if isExample {
		lines = redactSensitive(lines)
	}

	return marshalEnv(lines), nil
}

// parseEnvBlock converts a rendered env template string into envLine values.
func parseEnvBlock(rendered string) ([]envLine, error) {
	var out []envLine
	for _, raw := range strings.Split(strings.TrimSpace(rendered), "\n") {
		raw = strings.TrimSpace(raw)
		if raw == "" || strings.HasPrefix(raw, "#") {
			continue
		}
		idx := strings.IndexByte(raw, '=')
		if idx < 0 {
			return nil, fmt.Errorf("unexpected env line %q", raw)
		}
		out = append(out, kv(raw[:idx], raw[idx+1:]))
	}
	return out, nil
}

// sensitiveKeys are redacted (set to empty) in .env.example.
var sensitiveKeys = map[string]bool{
	"APP_KEY":        true,
	"DB_PASSWORD":    true,
	"DB_URL":         true,
	"REDIS_PASSWORD": true,
}

// redactSensitive returns a copy of lines with sensitive values cleared.
func redactSensitive(lines []envLine) []envLine {
	out := make([]envLine, len(lines))
	copy(out, lines)
	for i, line := range out {
		if !line.comment && sensitiveKeys[line.key] {
			out[i].value = ""
		}
	}
	return out
}

// marshalEnv serialises envLine values to a .env file string.
func marshalEnv(lines []envLine) string {
	var sb strings.Builder
	for _, line := range lines {
		if line.comment {
			if line.value == "" {
				sb.WriteByte('\n')
			} else {
				sb.WriteString(line.value)
				sb.WriteByte('\n')
			}
		} else {
			sb.WriteString(line.key)
			sb.WriteByte('=')
			sb.WriteString(line.value)
			sb.WriteByte('\n')
		}
	}
	return sb.String()
}
