package compose

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/phlisg/frank/internal/config"
)

// envLine is a single line in a .env file.
// Exactly one of three states applies:
//   - comment=true              → pure comment or blank line (never touched by merge)
//   - comment=false, disabled=true  → commented-out key (#KEY=value) — can be enabled by merge
//   - comment=false, disabled=false → active key=value pair
type envLine struct {
	comment  bool
	disabled bool
	key      string
	value    string
}

func comment(text string) envLine { return envLine{comment: true, value: text} }
func blank() envLine              { return envLine{comment: true, value: ""} }
func kv(key, value string) envLine {
	return envLine{key: key, value: value}
}
func disabled(key, value string) envLine {
	return envLine{disabled: true, key: key, value: value}
}

// envHeader is the standard generated-by comment.
const envHeader = "# Generated by Frank — edit frank.yaml, not this file"

// GenerateEnv produces a .env string for the given config and project name.
func (g *Generator) GenerateEnv(cfg *config.Config, projectName string) (string, error) {
	return g.buildEnv(cfg, projectName, false)
}

// GenerateEnvExample produces a .env.example string with placeholder values.
func (g *Generator) GenerateEnvExample(cfg *config.Config, projectName string) (string, error) {
	return g.buildEnv(cfg, projectName, true)
}

// WriteEnv generates .env and .env.example and writes both to dir.
func (g *Generator) WriteEnv(cfg *config.Config, projectName, dir string) error {
	env, err := g.GenerateEnv(cfg, projectName)
	if err != nil {
		return err
	}
	example, err := g.GenerateEnvExample(cfg, projectName)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, ".env"), []byte(env), 0644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, ".env.example"), []byte(example), 0644)
}

func (g *Generator) buildEnv(cfg *config.Config, projectName string, isExample bool) (string, error) {
	lines, err := g.loadLaravelBaseEnv(cfg.Laravel.Version, projectName)
	if err != nil {
		return "", err
	}

	for _, svc := range cfg.Services {
		svcCfg := cfg.Config[svc]
		rendered, err := g.engine.RenderServiceEnv(svc, svcCfg, projectName)
		if err != nil {
			return "", fmt.Errorf("service %q env: %w", svc, err)
		}

		block, err := parseEnvBlock(rendered)
		if err != nil {
			return "", fmt.Errorf("parse service %q env block: %w", svc, err)
		}

		lines = mergeEnvBlock(lines, svc, block)
	}

	if isExample {
		lines = redactSensitive(lines)
	}

	return marshalEnv(lines), nil
}

// loadLaravelBaseEnv reads and parses the version-appropriate Laravel .env.example template,
// prepending the Frank header and substituting APP_NAME with the project name.
func (g *Generator) loadLaravelBaseEnv(version, projectName string) ([]envLine, error) {
	templateVersion := "13.x" // default: latest
	switch version {
	case "11.x":
		templateVersion = "11.x"
	case "12.x":
		templateVersion = "12.x"
	}

	raw, err := g.engine.ReadFile(fmt.Sprintf("templates/laravel/%s/.env.example", templateVersion))
	if err != nil {
		return nil, fmt.Errorf("load laravel env template: %w", err)
	}

	lines := parseFullEnvFile(raw)
	for i, line := range lines {
		if !line.comment && line.key == "APP_NAME" {
			lines[i].value = projectName
			break
		}
	}

	return append([]envLine{comment(envHeader), blank()}, lines...), nil
}

// mergeEnvBlock merges a service env block into base lines.
// Keys that already exist as active lines are replaced in-place.
// Keys not found are appended as a labeled section.
func mergeEnvBlock(base []envLine, svc string, block []envLine) []envLine {
	keyIndex := map[string]int{}
	for i, line := range base {
		if !line.comment {
			keyIndex[line.key] = i
		}
	}

	result := make([]envLine, len(base))
	copy(result, base)

	var newLines []envLine
	for _, bline := range block {
		if idx, exists := keyIndex[bline.key]; exists {
			result[idx].value = bline.value
		} else {
			newLines = append(newLines, bline)
		}
	}

	if len(newLines) > 0 {
		result = append(result, blank(), comment(fmt.Sprintf("# %s", svc)))
		result = append(result, newLines...)
	}

	return result
}

// parseFullEnvFile parses a .env file string into envLine values, preserving all lines.
func parseFullEnvFile(content string) []envLine {
	var lines []envLine
	for _, raw := range strings.Split(content, "\n") {
		if raw == "" {
			lines = append(lines, blank())
			continue
		}
		if strings.HasPrefix(raw, "#") {
			lines = append(lines, comment(raw))
			continue
		}
		idx := strings.IndexByte(raw, '=')
		if idx < 0 {
			lines = append(lines, comment(raw))
			continue
		}
		lines = append(lines, kv(raw[:idx], raw[idx+1:]))
	}
	// trim trailing blank lines
	for len(lines) > 0 && lines[len(lines)-1].comment && lines[len(lines)-1].value == "" {
		lines = lines[:len(lines)-1]
	}
	return lines
}

// parseEnvBlock converts a rendered env template string into envLine values.
func parseEnvBlock(rendered string) ([]envLine, error) {
	var out []envLine
	for _, raw := range strings.Split(strings.TrimSpace(rendered), "\n") {
		raw = strings.TrimSpace(raw)
		if raw == "" || strings.HasPrefix(raw, "#") {
			continue
		}
		idx := strings.IndexByte(raw, '=')
		if idx < 0 {
			return nil, fmt.Errorf("unexpected env line %q", raw)
		}
		out = append(out, kv(raw[:idx], raw[idx+1:]))
	}
	return out, nil
}

// sensitiveKeys are redacted (set to empty) in .env.example.
var sensitiveKeys = map[string]bool{
	"APP_KEY":        true,
	"DB_PASSWORD":    true,
	"DB_URL":         true,
	"REDIS_PASSWORD": true,
}

// redactSensitive returns a copy of lines with sensitive values cleared.
func redactSensitive(lines []envLine) []envLine {
	out := make([]envLine, len(lines))
	copy(out, lines)
	for i, line := range out {
		if !line.comment && sensitiveKeys[line.key] {
			out[i].value = ""
		}
	}
	return out
}

// marshalEnv serialises envLine values to a .env file string.
func marshalEnv(lines []envLine) string {
	var sb strings.Builder
	for _, line := range lines {
		if line.comment {
			if line.value == "" {
				sb.WriteByte('\n')
			} else {
				sb.WriteString(line.value)
				sb.WriteByte('\n')
			}
		} else if line.disabled {
			sb.WriteByte('#')
			sb.WriteString(line.key)
			sb.WriteByte('=')
			sb.WriteString(line.value)
			sb.WriteByte('\n')
		} else {
			sb.WriteString(line.key)
			sb.WriteByte('=')
			sb.WriteString(line.value)
			sb.WriteByte('\n')
		}
	}
	return sb.String()
}
