package compose

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/phlisg/frank/internal/config"
)

// envLine is a single line in a .env file.
// Exactly one of three states applies:
//   - comment=true              → pure comment or blank line (never touched by merge)
//   - comment=false, disabled=true  → commented-out key (#KEY=value) — can be enabled by merge
//   - comment=false, disabled=false → active key=value pair
type envLine struct {
	comment  bool
	disabled bool
	key      string
	value    string
}

func comment(text string) envLine { return envLine{comment: true, value: text} }
func blank() envLine              { return envLine{comment: true, value: ""} }
func kv(key, value string) envLine {
	return envLine{key: key, value: value}
}
func disabled(key, value string) envLine {
	return envLine{disabled: true, key: key, value: value}
}

// envHeader is the standard generated-by comment.
const envHeader = "# Generated by Frank — edit frank.yaml, not this file"

// buildEnvLines builds the envLine slice for the given config and project name.
// If isExample is true, sensitive values are redacted.
func (g *Generator) buildEnvLines(cfg *config.Config, projectName string, isExample bool) ([]envLine, error) {
	lines, err := g.loadLaravelBaseEnv(cfg.Laravel.Version, projectName)
	if err != nil {
		return nil, err
	}
	for _, svc := range cfg.Services {
		svcCfg := cfg.Config[svc]
		rendered, err := g.engine.RenderServiceEnv(svc, svcCfg, projectName)
		if err != nil {
			return nil, fmt.Errorf("service %q env: %w", svc, err)
		}
		block, err := parseEnvBlock(rendered)
		if err != nil {
			return nil, fmt.Errorf("parse service %q env block: %w", svc, err)
		}
		lines = mergeEnvBlock(lines, svc, block)
	}
	if isExample {
		lines = redactSensitive(lines)
	}
	return lines, nil
}

// GenerateEnv produces a .env string for the given config and project name.
func (g *Generator) GenerateEnv(cfg *config.Config, projectName string) (string, error) {
	lines, err := g.buildEnvLines(cfg, projectName, false)
	if err != nil {
		return "", err
	}
	return marshalEnv(lines), nil
}

// GenerateEnvExample produces a .env.example string with placeholder values.
func (g *Generator) GenerateEnvExample(cfg *config.Config, projectName string) (string, error) {
	lines, err := g.buildEnvLines(cfg, projectName, true)
	if err != nil {
		return "", err
	}
	return marshalEnv(lines), nil
}

// readExistingAppKey reads APP_KEY from an existing .env at dir/.env.
// Returns "" if the file doesn't exist, is unreadable, or APP_KEY is blank.
func readExistingAppKey(dir string) string {
	data, err := os.ReadFile(filepath.Join(dir, ".env"))
	if err != nil {
		if !os.IsNotExist(err) {
			fmt.Fprintf(os.Stderr, "warning: could not read existing .env: %v\n", err)
		}
		return ""
	}
	for _, line := range strings.Split(string(data), "\n") {
		if strings.HasPrefix(line, "APP_KEY=") {
			val := strings.TrimPrefix(line, "APP_KEY=")
			return val // returns "" if blank
		}
	}
	return ""
}

// WriteEnv generates .env and .env.example and writes both to dir.
// If an existing .env is present with a non-blank APP_KEY (e.g. set by composer create-project),
// that key is injected into the generated .env at the envLine level so it is not lost.
func (g *Generator) WriteEnv(cfg *config.Config, projectName, dir string) error {
	existingKey := readExistingAppKey(dir) // read before writing

	envLines, err := g.buildEnvLines(cfg, projectName, false)
	if err != nil {
		return err
	}
	// Inject preserved APP_KEY into the envLine slice before marshaling.
	if existingKey != "" {
		for i, line := range envLines {
			if !line.comment && !line.disabled && line.key == "APP_KEY" {
				envLines[i].value = existingKey
				break
			}
		}
	}

	exampleLines, err := g.buildEnvLines(cfg, projectName, true)
	if err != nil {
		return err
	}

	if err := os.WriteFile(filepath.Join(dir, ".env"), []byte(marshalEnv(envLines)), 0644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, ".env.example"), []byte(marshalEnv(exampleLines)), 0644)
}

// loadLaravelBaseEnv reads and parses the version-appropriate Laravel .env.example template,
// prepending the Frank header and substituting APP_NAME with the project name.
func (g *Generator) loadLaravelBaseEnv(version, projectName string) ([]envLine, error) {
	templateVersion := "13.x" // default: latest
	switch version {
	case "11.x":
		templateVersion = "11.x"
	case "12.x":
		templateVersion = "12.x"
	}

	raw, err := g.engine.ReadFile(fmt.Sprintf("templates/laravel/%s/.env.example", templateVersion))
	if err != nil {
		return nil, fmt.Errorf("load laravel env template: %w", err)
	}

	lines := parseFullEnvFile(raw)
	for i, line := range lines {
		if !line.comment && !line.disabled && line.key == "APP_NAME" {
			lines[i].value = projectName
			break
		}
	}

	return append([]envLine{comment(envHeader), blank()}, lines...), nil
}

// mergeEnvBlock merges a service env block into base lines.
// Active and disabled keys are both indexed. Service vars replace active key values in-place,
// and enable (uncomment) disabled keys. Keys not found in the template are appended as extras.
func mergeEnvBlock(base []envLine, svc string, block []envLine) []envLine {
	// Index both active and disabled lines (anything with comment=false).
	keyIndex := map[string]int{}
	for i, line := range base {
		if !line.comment {
			keyIndex[line.key] = i
		}
	}

	result := make([]envLine, len(base))
	copy(result, base)

	var newLines []envLine
	for _, bline := range block {
		if idx, exists := keyIndex[bline.key]; exists {
			result[idx].value = bline.value
			result[idx].disabled = false // enable commented-out keys in-place
		} else {
			newLines = append(newLines, bline)
		}
	}

	if len(newLines) > 0 {
		result = append(result, blank(), comment(fmt.Sprintf("# %s", svc)))
		result = append(result, newLines...)
	}

	return result
}

// isEnvKey returns true if s is a valid env var name: starts with A-Z, followed by A-Z, 0-9, or _.
func isEnvKey(s string) bool {
	if s == "" {
		return false
	}
	for i, c := range s {
		if i == 0 && !(c >= 'A' && c <= 'Z') {
			return false
		}
		if i > 0 && !((c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_') {
			return false
		}
	}
	return true
}

// parseFullEnvFile parses a .env file string into envLine values, preserving all lines.
// Lines beginning with "#" are examined: if after stripping "#" and an optional space the
// remainder matches KEY=value (KEY is [A-Z][A-Z0-9_]*), it becomes a disabled envLine.
// Otherwise it is a pure comment. Parsing is liberal (accepts "# KEY=" and "#KEY=");
// serialisation is canonical (#KEY=value, no space).
func parseFullEnvFile(content string) []envLine {
	var lines []envLine
	for _, raw := range strings.Split(content, "\n") {
		if raw == "" {
			lines = append(lines, blank())
			continue
		}
		if strings.HasPrefix(raw, "#") {
			rest := raw[1:]
			if len(rest) > 0 && rest[0] == ' ' {
				rest = rest[1:]
			}
			if eqIdx := strings.IndexByte(rest, '='); eqIdx > 0 && isEnvKey(rest[:eqIdx]) {
				lines = append(lines, disabled(rest[:eqIdx], rest[eqIdx+1:]))
				continue
			}
			lines = append(lines, comment(raw))
			continue
		}
		eqIdx := strings.IndexByte(raw, '=')
		if eqIdx < 0 {
			lines = append(lines, comment(raw))
			continue
		}
		lines = append(lines, kv(raw[:eqIdx], raw[eqIdx+1:]))
	}
	// trim trailing blank lines
	for len(lines) > 0 && lines[len(lines)-1].comment && lines[len(lines)-1].value == "" {
		lines = lines[:len(lines)-1]
	}
	return lines
}

// parseEnvBlock converts a rendered env template string into envLine values.
func parseEnvBlock(rendered string) ([]envLine, error) {
	var out []envLine
	for _, raw := range strings.Split(strings.TrimSpace(rendered), "\n") {
		raw = strings.TrimSpace(raw)
		if raw == "" || strings.HasPrefix(raw, "#") {
			continue
		}
		idx := strings.IndexByte(raw, '=')
		if idx < 0 {
			return nil, fmt.Errorf("unexpected env line %q", raw)
		}
		out = append(out, kv(raw[:idx], raw[idx+1:]))
	}
	return out, nil
}

// sensitiveKeys are redacted (set to empty) in .env.example.
var sensitiveKeys = map[string]bool{
	"APP_KEY":        true,
	"DB_PASSWORD":    true,
	"DB_URL":         true,
	"REDIS_PASSWORD": true,
}

// redactSensitive returns a copy of lines with sensitive values cleared.
func redactSensitive(lines []envLine) []envLine {
	out := make([]envLine, len(lines))
	copy(out, lines)
	for i, line := range out {
		if !line.comment && sensitiveKeys[line.key] {
			out[i].value = ""
		}
	}
	return out
}

// marshalEnv serialises envLine values to a .env file string.
func marshalEnv(lines []envLine) string {
	var sb strings.Builder
	for _, line := range lines {
		if line.comment {
			if line.value == "" {
				sb.WriteByte('\n')
			} else {
				sb.WriteString(line.value)
				sb.WriteByte('\n')
			}
		} else if line.disabled {
			sb.WriteByte('#')
			sb.WriteString(line.key)
			sb.WriteByte('=')
			sb.WriteString(line.value)
			sb.WriteByte('\n')
		} else {
			sb.WriteString(line.key)
			sb.WriteByte('=')
			sb.WriteString(line.value)
			sb.WriteByte('\n')
		}
	}
	return sb.String()
}
