package compose

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/phlisg/frank/internal/config"
)

func TestGenerateEnv_BaseVars(t *testing.T) {
	g := newTestGenerator(t)
	cfg := config.New()

	out, err := g.GenerateEnv(cfg, "my-project")
	if err != nil {
		t.Fatalf("GenerateEnv error: %v", err)
	}

	checks := []string{
		"APP_NAME=my-project",
		"APP_ENV=local",
		"APP_KEY=",
		"APP_DEBUG=true",
		"APP_URL=http://localhost",
		"LOG_CHANNEL=stack",
		"SESSION_LIFETIME=120",
		`VITE_APP_NAME="${APP_NAME}"`,
		"# Generated by Frank",
	}
	for _, want := range checks {
		if !strings.Contains(out, want) {
			t.Errorf("expected %q in .env output", want)
		}
	}
}

func TestGenerateEnv_PgsqlOverridesDB(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Services: []string{"pgsql"},
	}

	out, err := g.GenerateEnv(cfg, "myapp")
	if err != nil {
		t.Fatalf("GenerateEnv error: %v", err)
	}

	checks := []string{
		"DB_CONNECTION=pgsql",
		"DB_HOST=pgsql",
		"DB_PORT=5432",
		"DB_DATABASE=myapp",
		"DB_USERNAME=sail",
		"DB_PASSWORD=password",
		"DB_SSLMODE=prefer",
	}
	for _, want := range checks {
		if !strings.Contains(out, want) {
			t.Errorf("expected %q in .env output", want)
		}
	}
}

func TestGenerateEnv_RedisOverridesCacheSession(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Services: []string{"pgsql", "redis"},
	}

	out, err := g.GenerateEnv(cfg, "myapp")
	if err != nil {
		t.Fatalf("GenerateEnv error: %v", err)
	}

	if !strings.Contains(out, "REDIS_HOST=redis") {
		t.Error("expected REDIS_HOST=redis")
	}
	if !strings.Contains(out, "CACHE_STORE=redis") {
		t.Error("expected CACHE_STORE=redis")
	}
	if !strings.Contains(out, "SESSION_DRIVER=redis") {
		t.Error("expected SESSION_DRIVER=redis")
	}
	if !strings.Contains(out, "QUEUE_CONNECTION=redis") {
		t.Error("expected QUEUE_CONNECTION=redis")
	}
}

func TestGenerateEnv_MailpitOverridesMail(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Services: []string{"pgsql", "mailpit"},
	}

	out, err := g.GenerateEnv(cfg, "myapp")
	if err != nil {
		t.Fatalf("GenerateEnv error: %v", err)
	}

	if !strings.Contains(out, "MAIL_MAILER=smtp") {
		t.Error("expected MAIL_MAILER=smtp")
	}
	if !strings.Contains(out, "MAIL_HOST=mailpit") {
		t.Error("expected MAIL_HOST=mailpit")
	}
	if !strings.Contains(out, "MAIL_PORT=1025") {
		t.Error("expected MAIL_PORT=1025")
	}
}

func TestGenerateEnv_MeilisearchOverridesScout(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Services: []string{"pgsql", "meilisearch"},
	}

	out, err := g.GenerateEnv(cfg, "myapp")
	if err != nil {
		t.Fatalf("GenerateEnv error: %v", err)
	}

	if !strings.Contains(out, "SCOUT_DRIVER=meilisearch") {
		t.Error("expected SCOUT_DRIVER=meilisearch")
	}
	if !strings.Contains(out, "MEILISEARCH_HOST=http://meilisearch:7700") {
		t.Error("expected MEILISEARCH_HOST")
	}
}

func TestGenerateEnv_Sqlite(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Services: []string{"sqlite"},
	}

	out, err := g.GenerateEnv(cfg, "myapp")
	if err != nil {
		t.Fatalf("GenerateEnv error: %v", err)
	}

	if !strings.Contains(out, "DB_CONNECTION=sqlite") {
		t.Error("expected DB_CONNECTION=sqlite")
	}
}

func TestGenerateEnvExample_RedactsSensitive(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Services: []string{"pgsql"},
	}

	out, err := g.GenerateEnvExample(cfg, "myapp")
	if err != nil {
		t.Fatalf("GenerateEnvExample error: %v", err)
	}

	if strings.Contains(out, "DB_PASSWORD=password") {
		t.Error(".env.example should not contain real DB_PASSWORD")
	}
	if !strings.Contains(out, "DB_PASSWORD=") {
		t.Error(".env.example should still have DB_PASSWORD key")
	}
	// APP_KEY should be empty in example
	if strings.Contains(out, "APP_KEY=base64") {
		t.Error(".env.example APP_KEY should be empty")
	}
}

func TestGenerateEnvExample_StructureMatchesEnv(t *testing.T) {
	g := newTestGenerator(t)
	cfg := config.New()

	env, err := g.GenerateEnv(cfg, "myapp")
	if err != nil {
		t.Fatalf("GenerateEnv error: %v", err)
	}
	example, err := g.GenerateEnvExample(cfg, "myapp")
	if err != nil {
		t.Fatalf("GenerateEnvExample error: %v", err)
	}

	// Both should have same keys
	envKeys := extractKeys(env)
	exampleKeys := extractKeys(example)
	if len(envKeys) != len(exampleKeys) {
		t.Errorf(".env has %d keys, .env.example has %d keys", len(envKeys), len(exampleKeys))
	}
}

func TestWriteEnv_CreatesBothFiles(t *testing.T) {
	g := newTestGenerator(t)
	cfg := config.New()
	dir := t.TempDir()

	if err := g.WriteEnv(cfg, "myapp", dir); err != nil {
		t.Fatalf("WriteEnv error: %v", err)
	}

	for _, name := range []string{".env", ".env.example"} {
		data, err := os.ReadFile(dir + "/" + name)
		if err != nil {
			t.Errorf("%s not created: %v", name, err)
			continue
		}
		if !strings.Contains(string(data), "APP_NAME=myapp") {
			t.Errorf("%s missing APP_NAME", name)
		}
	}
}

func TestGenerateEnv_Laravel11(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:     config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Laravel: config.Laravel{Version: "11.x"},
	}
	out, err := g.GenerateEnv(cfg, "myapp")
	if err != nil {
		t.Fatalf("GenerateEnv error: %v", err)
	}
	if !strings.Contains(out, "PHP_CLI_SERVER_WORKERS=4") {
		t.Error("expected PHP_CLI_SERVER_WORKERS=4 to be active for Laravel 11.x")
	}
	if strings.Contains(out, "#PHP_CLI_SERVER_WORKERS=4") {
		t.Error("PHP_CLI_SERVER_WORKERS should not be disabled for Laravel 11.x")
	}
}

func TestGenerateEnv_Laravel12(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:     config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Laravel: config.Laravel{Version: "12.x"},
	}
	out, err := g.GenerateEnv(cfg, "myapp")
	if err != nil {
		t.Fatalf("GenerateEnv error: %v", err)
	}
	// Must be present as a disabled key, not active
	if !strings.Contains(out, "#PHP_CLI_SERVER_WORKERS=4") {
		t.Error("expected #PHP_CLI_SERVER_WORKERS=4 (disabled) for Laravel 12.x")
	}
	if strings.Contains(out, "\nPHP_CLI_SERVER_WORKERS=4") {
		t.Error("PHP_CLI_SERVER_WORKERS must not be active for Laravel 12.x")
	}
}

func TestGenerateEnv_Laravel13(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:     config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Laravel: config.Laravel{Version: "13.x"},
	}
	out, err := g.GenerateEnv(cfg, "myapp")
	if err != nil {
		t.Fatalf("GenerateEnv error: %v", err)
	}
	// 13.x template is identical to 12.x — PHP_CLI_SERVER_WORKERS must not be active
	if strings.Contains(out, "\nPHP_CLI_SERVER_WORKERS=4") {
		t.Error("PHP_CLI_SERVER_WORKERS should not be active for Laravel 13.x")
	}
	// Verify it loaded (not a fallback error)
	if !strings.Contains(out, "APP_NAME=myapp") {
		t.Error("expected APP_NAME=myapp in output")
	}
}

func TestMarshalEnv_DisabledLine(t *testing.T) {
	lines := []envLine{
		kv("ACTIVE", "value"),
		{disabled: true, key: "DISABLED_KEY", value: "original"},
		comment("# a comment"),
	}
	out := marshalEnv(lines)
	if !strings.Contains(out, "ACTIVE=value\n") {
		t.Error("expected ACTIVE=value")
	}
	if !strings.Contains(out, "#DISABLED_KEY=original\n") {
		t.Error("expected #DISABLED_KEY=original (no space)")
	}
	if strings.Contains(out, "\nDISABLED_KEY=original\n") {
		t.Error("disabled key must not appear as active KEY=value")
	}
}

func TestParseFullEnvFile_DisabledKey(t *testing.T) {
	input := "ACTIVE=yes\n# DB_HOST=127.0.0.1\n#DB_PORT=3306\n# This is a comment\n"
	lines := parseFullEnvFile(input)

	var active, disabledHost, disabledPort, pureComment envLine
	for _, l := range lines {
		switch {
		case !l.comment && !l.disabled && l.key == "ACTIVE":
			active = l
		case l.disabled && l.key == "DB_HOST":
			disabledHost = l
		case l.disabled && l.key == "DB_PORT":
			disabledPort = l
		case l.comment && l.value == "# This is a comment":
			pureComment = l
		}
	}

	if active.key != "ACTIVE" || active.value != "yes" {
		t.Error("expected active ACTIVE=yes")
	}
	if disabledHost.key != "DB_HOST" || disabledHost.value != "127.0.0.1" {
		t.Errorf("expected disabled DB_HOST=127.0.0.1, got key=%q value=%q", disabledHost.key, disabledHost.value)
	}
	if disabledPort.key != "DB_PORT" || disabledPort.value != "3306" {
		t.Errorf("expected disabled DB_PORT=3306, got key=%q value=%q", disabledPort.key, disabledPort.value)
	}
	if pureComment.value != "# This is a comment" {
		t.Error("expected pure comment line preserved")
	}
}

func TestGenerateEnv_DisabledKeyEnabled(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Laravel:  config.Laravel{Version: "13.x"},
		Services: []string{"pgsql"},
	}
	out, err := g.GenerateEnv(cfg, "myapp")
	if err != nil {
		t.Fatalf("GenerateEnv error: %v", err)
	}
	// These were commented-out in the base template — should now be active
	for _, want := range []string{
		"DB_HOST=pgsql",
		"DB_PORT=5432",
		"DB_DATABASE=myapp",
		"DB_USERNAME=sail",
		"DB_PASSWORD=password",
	} {
		if !strings.Contains(out, want+"\n") {
			t.Errorf("expected active %q in output", want)
		}
		if strings.Contains(out, "#"+want) {
			t.Errorf("%q must not appear as a disabled key", want)
		}
	}
}

func TestGenerateEnv_DisabledKeyUnchanged(t *testing.T) {
	g := newTestGenerator(t)
	// No database service — DB_HOST should remain disabled
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Laravel:  config.Laravel{Version: "13.x"},
		Services: []string{},
	}
	out, err := g.GenerateEnv(cfg, "myapp")
	if err != nil {
		t.Fatalf("GenerateEnv error: %v", err)
	}
	if !strings.Contains(out, "#DB_HOST=127.0.0.1") {
		t.Error("expected #DB_HOST=127.0.0.1 (disabled) when no DB service configured")
	}
	if strings.Contains(out, "\nDB_HOST=") {
		t.Error("DB_HOST must not be active when no DB service is configured")
	}
}

func TestWriteEnv_AppKeyPreserved(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Laravel:  config.Laravel{Version: "13.x"},
		Services: []string{"pgsql"},
	}
	dir := t.TempDir()

	// Simulate a .env already written by composer create-project with a generated key.
	existing := "APP_KEY=base64:testkey==\nAPP_ENV=local\n"
	if err := os.WriteFile(filepath.Join(dir, ".env"), []byte(existing), 0644); err != nil {
		t.Fatalf("setup: %v", err)
	}

	if err := g.WriteEnv(cfg, "myapp", dir); err != nil {
		t.Fatalf("WriteEnv error: %v", err)
	}

	env, err := os.ReadFile(filepath.Join(dir, ".env"))
	if err != nil {
		t.Fatalf("read .env: %v", err)
	}
	example, err := os.ReadFile(filepath.Join(dir, ".env.example"))
	if err != nil {
		t.Fatalf("read .env.example: %v", err)
	}

	if !strings.Contains(string(env), "APP_KEY=base64:testkey==") {
		t.Errorf(".env should contain preserved APP_KEY, got:\n%s", string(env))
	}
	if strings.Contains(string(example), "APP_KEY=base64") {
		t.Error(".env.example must not contain real APP_KEY")
	}
	if !strings.Contains(string(example), "APP_KEY=") {
		t.Error(".env.example must still contain APP_KEY= key")
	}
}

// extractKeys returns all non-comment KEY names from a .env string.
func extractKeys(env string) []string {
	var keys []string
	for _, line := range strings.Split(env, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if idx := strings.IndexByte(line, '='); idx > 0 {
			keys = append(keys, line[:idx])
		}
	}
	return keys
}
