package compose

import (
	"os"
	"strings"
	"testing"

	"github.com/phlisg/frank/internal/config"
)

func TestGenerateEnv_BaseVars(t *testing.T) {
	g := newTestGenerator(t)
	cfg := config.New()

	out, err := g.GenerateEnv(cfg, "my-project")
	if err != nil {
		t.Fatalf("GenerateEnv error: %v", err)
	}

	checks := []string{
		"APP_NAME=my-project",
		"APP_ENV=local",
		"APP_KEY=",
		"APP_DEBUG=true",
		"APP_URL=http://localhost",
		"LOG_CHANNEL=stack",
		"SESSION_LIFETIME=120",
		"VITE_APP_NAME=${APP_NAME}",
		"# Generated by Frank",
	}
	for _, want := range checks {
		if !strings.Contains(out, want) {
			t.Errorf("expected %q in .env output", want)
		}
	}
}

func TestGenerateEnv_PgsqlOverridesDB(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Services: []string{"pgsql"},
	}

	out, err := g.GenerateEnv(cfg, "myapp")
	if err != nil {
		t.Fatalf("GenerateEnv error: %v", err)
	}

	checks := []string{
		"DB_CONNECTION=pgsql",
		"DB_HOST=pgsql",
		"DB_PORT=5432",
		"DB_DATABASE=myapp",
		"DB_USERNAME=sail",
		"DB_PASSWORD=password",
		"DB_SSLMODE=prefer",
	}
	for _, want := range checks {
		if !strings.Contains(out, want) {
			t.Errorf("expected %q in .env output", want)
		}
	}
}

func TestGenerateEnv_RedisOverridesCacheSession(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Services: []string{"pgsql", "redis"},
	}

	out, err := g.GenerateEnv(cfg, "myapp")
	if err != nil {
		t.Fatalf("GenerateEnv error: %v", err)
	}

	if !strings.Contains(out, "REDIS_HOST=redis") {
		t.Error("expected REDIS_HOST=redis")
	}
	if !strings.Contains(out, "CACHE_STORE=redis") {
		t.Error("expected CACHE_STORE=redis")
	}
	if !strings.Contains(out, "SESSION_DRIVER=redis") {
		t.Error("expected SESSION_DRIVER=redis")
	}
	if !strings.Contains(out, "QUEUE_CONNECTION=redis") {
		t.Error("expected QUEUE_CONNECTION=redis")
	}
}

func TestGenerateEnv_MailpitOverridesMail(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Services: []string{"pgsql", "mailpit"},
	}

	out, err := g.GenerateEnv(cfg, "myapp")
	if err != nil {
		t.Fatalf("GenerateEnv error: %v", err)
	}

	if !strings.Contains(out, "MAIL_MAILER=smtp") {
		t.Error("expected MAIL_MAILER=smtp")
	}
	if !strings.Contains(out, "MAIL_HOST=mailpit") {
		t.Error("expected MAIL_HOST=mailpit")
	}
	if !strings.Contains(out, "MAIL_PORT=1025") {
		t.Error("expected MAIL_PORT=1025")
	}
}

func TestGenerateEnv_MeilisearchOverridesScout(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Services: []string{"pgsql", "meilisearch"},
	}

	out, err := g.GenerateEnv(cfg, "myapp")
	if err != nil {
		t.Fatalf("GenerateEnv error: %v", err)
	}

	if !strings.Contains(out, "SCOUT_DRIVER=meilisearch") {
		t.Error("expected SCOUT_DRIVER=meilisearch")
	}
	if !strings.Contains(out, "MEILISEARCH_HOST=http://meilisearch:7700") {
		t.Error("expected MEILISEARCH_HOST")
	}
}

func TestGenerateEnv_Sqlite(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Services: []string{"sqlite"},
	}

	out, err := g.GenerateEnv(cfg, "myapp")
	if err != nil {
		t.Fatalf("GenerateEnv error: %v", err)
	}

	if !strings.Contains(out, "DB_CONNECTION=sqlite") {
		t.Error("expected DB_CONNECTION=sqlite")
	}
}

func TestGenerateEnvExample_RedactsSensitive(t *testing.T) {
	g := newTestGenerator(t)
	cfg := &config.Config{
		PHP:      config.PHP{Version: "8.5", Runtime: "frankenphp"},
		Services: []string{"pgsql"},
	}

	out, err := g.GenerateEnvExample(cfg, "myapp")
	if err != nil {
		t.Fatalf("GenerateEnvExample error: %v", err)
	}

	if strings.Contains(out, "DB_PASSWORD=password") {
		t.Error(".env.example should not contain real DB_PASSWORD")
	}
	if !strings.Contains(out, "DB_PASSWORD=") {
		t.Error(".env.example should still have DB_PASSWORD key")
	}
	// APP_KEY should be empty in example
	if strings.Contains(out, "APP_KEY=base64") {
		t.Error(".env.example APP_KEY should be empty")
	}
}

func TestGenerateEnvExample_StructureMatchesEnv(t *testing.T) {
	g := newTestGenerator(t)
	cfg := config.New()

	env, err := g.GenerateEnv(cfg, "myapp")
	if err != nil {
		t.Fatalf("GenerateEnv error: %v", err)
	}
	example, err := g.GenerateEnvExample(cfg, "myapp")
	if err != nil {
		t.Fatalf("GenerateEnvExample error: %v", err)
	}

	// Both should have same keys
	envKeys := extractKeys(env)
	exampleKeys := extractKeys(example)
	if len(envKeys) != len(exampleKeys) {
		t.Errorf(".env has %d keys, .env.example has %d keys", len(envKeys), len(exampleKeys))
	}
}

func TestWriteEnv_CreatesBothFiles(t *testing.T) {
	g := newTestGenerator(t)
	cfg := config.New()
	dir := t.TempDir()

	if err := g.WriteEnv(cfg, "myapp", dir); err != nil {
		t.Fatalf("WriteEnv error: %v", err)
	}

	for _, name := range []string{".env", ".env.example"} {
		data, err := os.ReadFile(dir + "/" + name)
		if err != nil {
			t.Errorf("%s not created: %v", name, err)
			continue
		}
		if !strings.Contains(string(data), "APP_NAME=myapp") {
			t.Errorf("%s missing APP_NAME", name)
		}
	}
}

// extractKeys returns all non-comment KEY names from a .env string.
func extractKeys(env string) []string {
	var keys []string
	for _, line := range strings.Split(env, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if idx := strings.IndexByte(line, '='); idx > 0 {
			keys = append(keys, line[:idx])
		}
	}
	return keys
}
