app:
  build:
    context: .
    dockerfile: Dockerfile
  networks:
    - frank
  volumes:
    - .:/app
  environment:
    - APP_ENV=local
    - APP_DEBUG=true
    - PSYSH_CONFIG=/app/.psysh.php
    - PSYSH_HOME=/app/storage/psysh
  env_file:
    - .env
  working_dir: /app
  tty: true
  user: "${UID:-1000}:${GID:-1000}"
  stdin_open: true

nginx:
  build:
    context: .
    dockerfile: nginx.Dockerfile
  ports:
    - "8000:8000"
    - "5173:5173"
  networks:
    - frank
  volumes:
    - .:/app
  depends_on:
    - app
