app:
  build:
    context: .
  ports:
    - "8000:8000"
    - "5173:5173"
    - "2019:2019"
  networks:
    - frank
  volumes:
    - .:/app
  environment:
    - APP_ENV=local
    - APP_DEBUG=true
    - SERVER_NAME=:8000
    - PSYSH_CONFIG=/app/.psysh.php
    - PSYSH_HOME=/app/storage/psysh
  env_file:
    - .env
  working_dir: /app
  tty: true
  user: "${UID:-1000}:${GID:-1000}"
  stdin_open: true
