// Generated by Frank — Vite dev server config
export default {
    host: '0.0.0.0',
    watch: {
        ignored: ['**/vendor/**', '**/node_modules/**', '**/storage/**', '**/public/**', '**/.frank/**', '**/.git/**'],
    },
};
