#!/usr/bin/env bash
# frank/scripts/sail-export.sh — export frank.yaml as Sail-compatible docker-compose.yml
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/config.sh"

OUTPUT_FILE=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        -f) OUTPUT_FILE="$2"; shift 2 ;;
        *)  echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
done

OUTPUT_FILE="${OUTPUT_FILE:-./docker-compose.yml}"

if ! frank_yaml_exists; then
    echo "Error: frank.yaml not found." >&2
    exit 1
fi

PHP_VERSION=$(frank_config_get '.php.version' "$DEFAULT_PHP_VERSION")
SERVICES=$(frank_services)

echo "📦 Exporting Sail-compatible compose to: $OUTPUT_FILE"

# Start building the Sail compose
cat > "$OUTPUT_FILE" << 'EOF'
# Generated by Frank (Sail export) — this is a best-effort Sail-compatible compose
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/PHP_VERSION_PLACEHOLDER
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-PHP_VERSION_PLACEHOLDER/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
EOF

# Replace PHP version placeholder
sed -i "s/PHP_VERSION_PLACEHOLDER/$PHP_VERSION/g" "$OUTPUT_FILE"

# Add each service in Sail format
for service in $SERVICES; do
    case "$service" in
        pgsql)
            cat >> "$OUTPUT_FILE" << 'EOF'
    pgsql:
        image: 'postgres:17'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-password}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
            retries: 3
            timeout: 5s
EOF
            ;;
        mysql)
            cat >> "$OUTPUT_FILE" << 'EOF'
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
EOF
            ;;
        redis)
            cat >> "$OUTPUT_FILE" << 'EOF'
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
EOF
            ;;
        meilisearch)
            cat >> "$OUTPUT_FILE" << 'EOF'
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        environment:
            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
        volumes:
            - 'sail-meilisearch:/meili_data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--spider", "http://127.0.0.1:7700/health"]
            retries: 3
            timeout: 5s
EOF
            ;;
        mariadb)
            cat >> "$OUTPUT_FILE" << 'EOF'
    mariadb:
        image: 'mariadb:11'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
            MARIADB_ROOT_HOST: '%'
            MARIADB_DATABASE: '${DB_DATABASE}'
            MARIADB_USER: '${DB_USERNAME}'
            MARIADB_PASSWORD: '${DB_PASSWORD}'
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
        volumes:
            - 'sail-mariadb:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            retries: 3
            timeout: 5s
EOF
            ;;
        memcached)
            cat >> "$OUTPUT_FILE" << 'EOF'
    memcached:
        image: 'memcached:alpine'
        ports:
            - '${FORWARD_MEMCACHED_PORT:-11211}:11211'
        networks:
            - sail
EOF
            ;;
        mailpit)
            cat >> "$OUTPUT_FILE" << 'EOF'
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
EOF
            ;;
    esac
done

# Add networks and volumes
cat >> "$OUTPUT_FILE" << 'EOF'
networks:
    sail:
        driver: bridge
volumes:
EOF

for service in $SERVICES; do
    case "$service" in
        pgsql)       echo "    sail-pgsql:" >> "$OUTPUT_FILE" ;;
        mysql)       echo "    sail-mysql:" >> "$OUTPUT_FILE" ;;
        mariadb)     echo "    sail-mariadb:" >> "$OUTPUT_FILE" ;;
        redis)       echo "    sail-redis:" >> "$OUTPUT_FILE" ;;
        meilisearch) echo "    sail-meilisearch:" >> "$OUTPUT_FILE" ;;
        memcached)   echo "    sail-memcached:" >> "$OUTPUT_FILE" ;;
    esac
done

# Add depends_on to laravel.test
DEPENDS=""
for service in $SERVICES; do
    case "$service" in
        pgsql|mysql|mariadb|redis|meilisearch|memcached)
            DEPENDS="${DEPENDS}\n            - ${service}"
            ;;
    esac
done
if [ -n "$DEPENDS" ]; then
    sed -i "/IGNITION_LOCAL_SITES_PATH/a\\        depends_on:$(echo -e "$DEPENDS")" "$OUTPUT_FILE"
fi

echo "✅ Sail-compatible compose written to: $OUTPUT_FILE"
echo ""
echo "⚠️  This is a best-effort export. You may need to:"
echo "   1. Run 'php artisan sail:install' for full Sail vendor setup"
echo "   2. Review and adjust the generated compose file"
