package cmd

import (
	"fmt"
	"path/filepath"

	"github.com/phlisg/frank/internal/config"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

func init() {
	rootCmd.AddCommand(addCmd)
}

var addCmd = &cobra.Command{
	Use:          "add <service>",
	Short:        "Add a service to frank.yaml and regenerate",
	Args:         cobra.ExactArgs(1),
	SilenceUsage: true,
	ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		if len(args) == 0 {
			return config.AllServices(), cobra.ShellCompDirectiveNoFileComp
		}
		return nil, cobra.ShellCompDirectiveNoFileComp
	},
	RunE: runAdd,
}

func runAdd(cmd *cobra.Command, args []string) error {
	service := args[0]
	dir := resolveDir()

	if !config.ValidService(service) {
		return fmt.Errorf("unsupported service %q — valid options: pgsql, mysql, mariadb, sqlite, redis, memcached, meilisearch, mailpit", service)
	}

	cfg, err := config.Load(dir)
	if err != nil {
		return err
	}

	if cfg.HasService(service) {
		return fmt.Errorf("service %q is already configured", service)
	}

	if config.IsDatabase(service) && cfg.Database() != "" {
		return fmt.Errorf("cannot add %q: %q is already configured (only one database allowed)", service, cfg.Database())
	}

	cfg.Services = append(cfg.Services, service)

	if err := saveConfig(cfg, dir); err != nil {
		return err
	}
	fmt.Printf("  added    %s\n", service)

	fmt.Println("\nRegenerating Docker files...")
	return generate(cfg, dir)
}

func saveConfig(cfg *config.Config, dir string) error {
	type configOutput struct {
		Version  int                             `yaml:"version"`
		PHP      config.PHP                      `yaml:"php"`
		Laravel  config.Laravel                  `yaml:"laravel"`
		Services []string                        `yaml:"services"`
		Config   map[string]config.ServiceConfig `yaml:"config,omitempty"`
	}
	out := configOutput{
		Version:  cfg.Version,
		PHP:      cfg.PHP,
		Laravel:  cfg.Laravel,
		Services: cfg.Services,
		Config:   cfg.Config,
	}
	b, err := yaml.Marshal(out)
	if err != nil {
		return fmt.Errorf("marshal frank.yaml: %w", err)
	}
	header := "# Generated by Frank — edit this file to customise your environment\n\n"
	content := header + string(b)
	return writeFile(filepath.Join(dir, config.ConfigFileName), content)
}
