package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/phlisg/frank/internal/cert"
	"github.com/phlisg/frank/internal/compose"
	"github.com/phlisg/frank/internal/config"
	"github.com/phlisg/frank/internal/output"
	"github.com/phlisg/frank/internal/template"
	"github.com/phlisg/frank/internal/tool"
	"github.com/spf13/cobra"
)

func init() {
	rootCmd.AddCommand(generateCmd)
}

var generateCmd = &cobra.Command{
	Use:               "generate",
	Short:             "Generate Docker files from frank.yaml",
	SilenceUsage:      true,
	ValidArgsFunction: cobra.NoFileCompletions,
	RunE: func(cmd *cobra.Command, args []string) error {
		dir := resolveDir()
		cfg, err := config.Load(dir)
		if err != nil {
			return err
		}
		stopGen := output.Spin("Generating Docker files")
		if err := generate(cfg, dir, rootCmd.Version); err != nil {
			stopGen(err)
			return err
		}
		stopGen(nil)

		// Phase 2: reconcile project-root tool config files
		if len(cfg.Tools) > 0 {
			stopTools := output.Spin("Installing dev tools")
			res, err := tool.Install(cfg.Tools, dir)
			if err != nil {
				stopTools(err)
				return err
			}
			stopTools(nil)
			output.Detail(fmt.Sprintf("%d created, %d skipped", len(res.Created), len(res.Skipped)))
		}

		if cfg.Server.IsHTTPS() {
			printViteHTTPSHint(dir)
		}
		output.NextSteps([]string{"frank up -d"})
		return nil
	},
}

// generate runs the full file generation pipeline for cfg into dir.
// Called by both `frank generate` and at the end of `frank new`.
func generate(cfg *config.Config, dir, version string) error {
	projectName := config.ProjectName(dir)
	engine := template.New(TemplateFS)
	gen := compose.New(engine)

	// Create .frank/ directory first.
	frankDir := filepath.Join(dir, ".frank")
	if err := os.MkdirAll(frankDir, 0755); err != nil {
		return fmt.Errorf("create .frank directory: %w", err)
	}

	// Generate TLS certs if HTTPS enabled.
	if cfg.Server.IsHTTPS() {
		result, err := cert.Generate(frankDir)
		if err != nil {
			return fmt.Errorf("cert generation: %w", err)
		}
		switch {
		case result.Generated:
			output.Detail("generated TLS certificates")
			if result.CANotTrusted {
				output.Warning("mkcert CA not trusted — run `mkcert -install` for browser-trusted certs")
			}
		case result.Skipped:
			output.Detail("TLS certificates already exist")
		case result.MkcertMissing:
			output.Warning("mkcert not found — install mkcert and re-run `frank generate` for HTTPS\n  https://github.com/FiloSottile/mkcert#installation")
		}
	}

	if err := gen.Write(cfg, projectName, dir); err != nil {
		return fmt.Errorf("generate compose.yaml: %w", err)
	}
	output.Detail("wrote .frank/compose.yaml")

	if err := gen.WriteEnv(cfg, projectName, dir); err != nil {
		return fmt.Errorf("generate .env: %w", err)
	}
	output.Detail("wrote .env")
	output.Detail("wrote .env.example")

	data := template.Data{
		PHPVersion:  cfg.PHP.Version,
		ProjectName: projectName,
		HTTPS:       cfg.Server.IsHTTPS(),
		ServerPort:  cfg.Server.EffectivePort(),
		CustomPort:  cfg.Server.Port != 0,
	}

	dockerfile, err := engine.RenderRuntime(cfg.PHP.Runtime, "Dockerfile.tmpl", data)
	if err != nil {
		return fmt.Errorf("render Dockerfile: %w", err)
	}
	if err := writeFile(filepath.Join(frankDir, "Dockerfile"), dockerfile); err != nil {
		return err
	}
	output.Detail("wrote .frank/Dockerfile")

	switch cfg.PHP.Runtime {
	case "frankenphp":
		caddyfile, err := engine.RenderRuntime("frankenphp", "Caddyfile.tmpl", data)
		if err != nil {
			return fmt.Errorf("render Caddyfile: %w", err)
		}
		if err := writeFile(filepath.Join(frankDir, "Caddyfile"), caddyfile); err != nil {
			return err
		}
		output.Detail("wrote .frank/Caddyfile")

	case "fpm":
		nginxConf, err := engine.RenderRuntime("fpm", "nginx.conf.tmpl", data)
		if err != nil {
			return fmt.Errorf("render nginx.conf: %w", err)
		}
		if err := writeFile(filepath.Join(frankDir, "nginx.conf"), nginxConf); err != nil {
			return err
		}
		output.Detail("wrote .frank/nginx.conf")

		nginxDockerfile, err := engine.RenderRuntime("fpm", "nginx.Dockerfile.tmpl", data)
		if err != nil {
			return fmt.Errorf("render nginx.Dockerfile: %w", err)
		}
		if err := writeFile(filepath.Join(frankDir, "nginx.Dockerfile"), nginxDockerfile); err != nil {
			return err
		}
		output.Detail("wrote .frank/nginx.Dockerfile")
	}

	// Write .frank/.state JSON.
	type frankState struct {
		PHPVersion   string `json:"phpVersion"`
		Runtime      string `json:"runtime"`
		FrankVersion string `json:"frankVersion"`
	}
	stateJSON, _ := json.Marshal(frankState{
		PHPVersion:   cfg.PHP.Version,
		Runtime:      cfg.PHP.Runtime,
		FrankVersion: version,
	})
	if err := os.WriteFile(filepath.Join(frankDir, ".state"), stateJSON, 0644); err != nil {
		return fmt.Errorf("write .frank/.state: %w", err)
	}

	// Write .frank/README.md.
	readme := "# Frank Docker Environment\n\nGenerated by [Frank](https://github.com/phlisg/frank) — edit `frank.yaml`, not these files.\n\n## Commands\n\n- `frank up` — start containers\n- `frank down` — stop containers\n- `frank generate` — regenerate after changing `frank.yaml`\n- `frank reset` — reset project to clean state\n\n## Version Control\n\nCommit the `.frank/` folder to version control so your team gets the same environment.\n\n## Eject to Sail\n\nRun `frank eject` to hand the project off to Laravel Sail.\n"
	if err := os.WriteFile(filepath.Join(frankDir, "README.md"), []byte(readme), 0644); err != nil {
		return fmt.Errorf("write .frank/README.md: %w", err)
	}

	// Write testing database init script for non-sqlite databases.
	db := cfg.Database()
	if db != "" && db != "sqlite" {
		scriptsDir := filepath.Join(frankDir, "scripts")
		if err := os.MkdirAll(scriptsDir, 0755); err != nil {
			return fmt.Errorf("create .frank/scripts directory: %w", err)
		}

		// Clean up stale init scripts from previous engine (e.g. .sql leftover after switching to mysql).
		for _, ext := range []string{".sql", ".sh"} {
			_ = os.Remove(filepath.Join(scriptsDir, "create-testing-database"+ext))
		}

		var tmplPath, outFile string
		switch db {
		case "pgsql":
			tmplPath = "templates/services/pgsql/create-testing-database.sql"
			outFile = "create-testing-database.sql"
		case "mysql":
			tmplPath = "templates/services/mysql/create-testing-database.sh"
			outFile = "create-testing-database.sh"
		case "mariadb":
			tmplPath = "templates/services/mariadb/create-testing-database.sh"
			outFile = "create-testing-database.sh"
		}

		content, err := engine.ReadFile(tmplPath)
		if err != nil {
			return fmt.Errorf("read init script template: %w", err)
		}
		if err := writeFile(filepath.Join(scriptsDir, outFile), content); err != nil {
			return err
		}
		output.Detail("wrote .frank/scripts/" + outFile)
	}

	// Patch phpunit.xml with the correct DB_CONNECTION for testing.
	if err := compose.PatchPHPUnitXML(dir, db); err != nil {
		return fmt.Errorf("patch phpunit.xml: %w", err)
	}

	// Ensure .frank/ is in root .gitignore.
	gitignorePath := filepath.Join(dir, ".gitignore")
	if err := ensureGitignoreLine(gitignorePath, ".frank/"); err != nil {
		fmt.Fprintf(os.Stderr, "warning: could not update .gitignore: %v\n", err)
	}

	// Ensure .frank/certs/ is gitignored (private keys must not be committed).
	if cfg.Server.IsHTTPS() {
		ensureCertsGitignore(dir)
	}

	// Write .frank/vite-server.js for Vite dev server config.
	viteServer := buildViteServerJS(cfg)
	if err := os.WriteFile(filepath.Join(frankDir, "vite-server.js"), []byte(viteServer), 0644); err != nil {
		return fmt.Errorf("write .frank/vite-server.js: %w", err)
	}
	output.Detail("wrote .frank/vite-server.js")

	// Migration: delete leftover Frank files at project root.
	legacyFiles := []string{"compose.yaml", "Dockerfile", "nginx.conf", "nginx.Dockerfile", "Caddyfile"}
	for _, name := range legacyFiles {
		p := filepath.Join(dir, name)
		if err := os.Remove(p); err == nil {
			output.Detail(fmt.Sprintf("removed %s (moved to .frank/)", name))
		}
	}

	return nil
}

func buildViteServerJS(cfg *config.Config) string {
	if !cfg.Server.IsHTTPS() {
		return "// Generated by Frank — Vite dev server config\nexport default {\n    host: '0.0.0.0',\n};\n"
	}
	return `// Generated by Frank — Vite dev server config
import fs from 'fs';

export default {
    host: '0.0.0.0',
    https: {
        key: fs.readFileSync('.frank/certs/localhost-key.pem'),
        cert: fs.readFileSync('.frank/certs/localhost.pem'),
    },
    origin: 'https://localhost:5173',
    cors: true,
};
`
}

func printViteHTTPSHint(dir string) {
	if viteConfigHasFrankServer(dir) {
		return
	}
	output.Warning(`HTTPS enabled — add to your vite.config.js/ts:

  import frankServer from './.frank/vite-server.js';

  // inside defineConfig:
  server: frankServer,`)
}

func viteConfigHasFrankServer(dir string) bool {
	for _, name := range []string{"vite.config.ts", "vite.config.js"} {
		data, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			continue
		}
		if strings.Contains(string(data), "vite-server") {
			return true
		}
	}
	return false
}

func generatedFileCount(cfg *config.Config) int {
	count := 6 // compose.yaml + .env + .env.example + Dockerfile + .state + README.md
	switch cfg.PHP.Runtime {
	case "frankenphp":
		count++ // Caddyfile
	case "fpm":
		count += 2 // nginx.conf + nginx.Dockerfile
	}
	db := cfg.Database()
	if db != "" && db != "sqlite" {
		count++ // init script
	}
	return count
}

func ensureGitignoreLine(path, line string) error {
	data, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	if strings.Contains(string(data), line) {
		return nil
	}
	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = fmt.Fprintf(f, "\n%s\n", line)
	return err
}

// ensureCertsGitignore ensures .frank/certs/ is listed in the project .gitignore.
// Best-effort — silently ignores errors.
func ensureCertsGitignore(dir string) {
	gitignorePath := filepath.Join(dir, ".gitignore")
	entry := ".frank/certs/"

	data, _ := os.ReadFile(gitignorePath)
	if strings.Contains(string(data), entry) {
		return
	}

	f, err := os.OpenFile(gitignorePath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return
	}
	defer f.Close()

	content := string(data)
	if len(content) > 0 && !strings.HasSuffix(content, "\n") {
		f.WriteString("\n")
	}
	f.WriteString(entry + "\n")
}
