package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/phlisg/frank/internal/compose"
	"github.com/phlisg/frank/internal/config"
	"github.com/phlisg/frank/internal/template"
	"github.com/phlisg/frank/internal/tool"
	"github.com/spf13/cobra"
)

func init() {
	rootCmd.AddCommand(generateCmd)
}

var generateCmd = &cobra.Command{
	Use:               "generate",
	Short:             "Generate Docker files from frank.yaml",
	SilenceUsage:      true,
	ValidArgsFunction: cobra.NoFileCompletions,
	RunE: func(cmd *cobra.Command, args []string) error {
		dir := resolveDir()
		cfg, err := config.Load(dir)
		if err != nil {
			return err
		}
		if err := generate(cfg, dir); err != nil {
			return err
		}

		// Phase 2: reconcile project-root tool config files
		if len(cfg.Tools) > 0 {
			fmt.Println("\nReconciling dev tools...")
			if _, err := tool.Install(cfg.Tools, dir); err != nil {
				return err
			}
		}

		return nil
	},
}

// generate runs the full file generation pipeline for cfg into dir.
// Called by both `frank generate` and at the end of `frank init`.
func generate(cfg *config.Config, dir string) error {
	projectName := config.ProjectName(dir)
	engine := template.New(TemplateFS)
	gen := compose.New(engine)

	// Create .frank/ directory first.
	frankDir := filepath.Join(dir, ".frank")
	if err := os.MkdirAll(frankDir, 0755); err != nil {
		return fmt.Errorf("create .frank directory: %w", err)
	}

	if err := gen.Write(cfg, projectName, dir); err != nil {
		return fmt.Errorf("generate compose.yaml: %w", err)
	}
	fmt.Println("  wrote  .frank/compose.yaml")

	if err := gen.WriteEnv(cfg, projectName, dir); err != nil {
		return fmt.Errorf("generate .env: %w", err)
	}
	fmt.Println("  wrote  .env")
	fmt.Println("  wrote  .env.example")

	data := template.Data{
		PHPVersion:  cfg.PHP.Version,
		ProjectName: projectName,
	}

	dockerfile, err := engine.RenderRuntime(cfg.PHP.Runtime, "Dockerfile.tmpl", data)
	if err != nil {
		return fmt.Errorf("render Dockerfile: %w", err)
	}
	if err := writeFile(filepath.Join(frankDir, "Dockerfile"), dockerfile); err != nil {
		return err
	}
	fmt.Println("  wrote  .frank/Dockerfile")

	switch cfg.PHP.Runtime {
	case "frankenphp":
		caddyfile, err := engine.RenderRuntime("frankenphp", "Caddyfile.tmpl", data)
		if err != nil {
			return fmt.Errorf("render Caddyfile: %w", err)
		}
		if err := writeFile(filepath.Join(frankDir, "Caddyfile"), caddyfile); err != nil {
			return err
		}
		fmt.Println("  wrote  .frank/Caddyfile")

	case "fpm":
		nginxConf, err := engine.RenderRuntime("fpm", "nginx.conf.tmpl", data)
		if err != nil {
			return fmt.Errorf("render nginx.conf: %w", err)
		}
		if err := writeFile(filepath.Join(frankDir, "nginx.conf"), nginxConf); err != nil {
			return err
		}
		fmt.Println("  wrote  .frank/nginx.conf")

		nginxDockerfile, err := engine.RenderRuntime("fpm", "nginx.Dockerfile.tmpl", data)
		if err != nil {
			return fmt.Errorf("render nginx.Dockerfile: %w", err)
		}
		if err := writeFile(filepath.Join(frankDir, "nginx.Dockerfile"), nginxDockerfile); err != nil {
			return err
		}
		fmt.Println("  wrote  .frank/nginx.Dockerfile")
	}

	// Write .frank/.state JSON.
	type frankState struct {
		PHPVersion string `json:"phpVersion"`
		Runtime    string `json:"runtime"`
	}
	stateJSON, _ := json.Marshal(frankState{PHPVersion: cfg.PHP.Version, Runtime: cfg.PHP.Runtime})
	if err := os.WriteFile(filepath.Join(frankDir, ".state"), stateJSON, 0644); err != nil {
		return fmt.Errorf("write .frank/.state: %w", err)
	}

	// Write .frank/README.md.
	readme := "# Frank Docker Environment\n\nGenerated by [Frank](https://github.com/phlisg/frank) — edit `frank.yaml`, not these files.\n\n## Commands\n\n- `frank up` — start containers\n- `frank down` — stop containers\n- `frank generate` — regenerate after changing `frank.yaml`\n- `frank reset` — reset project to clean state\n\n## Version Control\n\nCommit the `.frank/` folder to version control so your team gets the same environment.\n\n## Eject to Sail\n\nRun `frank eject` to hand the project off to Laravel Sail.\n"
	if err := os.WriteFile(filepath.Join(frankDir, "README.md"), []byte(readme), 0644); err != nil {
		return fmt.Errorf("write .frank/README.md: %w", err)
	}

	// Ensure .frank/ is in root .gitignore.
	gitignorePath := filepath.Join(dir, ".gitignore")
	if err := ensureGitignoreLine(gitignorePath, ".frank/"); err != nil {
		fmt.Fprintf(os.Stderr, "warning: could not update .gitignore: %v\n", err)
	}

	// Migration: delete leftover Frank files at project root.
	legacyFiles := []string{"compose.yaml", "Dockerfile", "nginx.conf", "nginx.Dockerfile", "Caddyfile"}
	for _, name := range legacyFiles {
		p := filepath.Join(dir, name)
		if err := os.Remove(p); err == nil {
			fmt.Printf("  removed  %s (moved to .frank/)\n", name)
		}
	}

	return nil
}

func ensureGitignoreLine(path, line string) error {
	data, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	if strings.Contains(string(data), line) {
		return nil
	}
	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = fmt.Fprintf(f, "\n%s\n", line)
	return err
}
