// Generated by Frank — Vite dev server config
import fs from 'fs';

export default {
    host: '0.0.0.0',
    https: {
        key: fs.readFileSync('.frank/certs/localhost-key.pem'),
        cert: fs.readFileSync('.frank/certs/localhost.pem'),
    },
    origin: 'https://localhost:5173',
    cors: true,
    watch: {
        ignored: ['**/vendor/**', '**/node_modules/**', '**/storage/**', '**/public/**', '**/.frank/**', '**/.git/**'],
    },
};
