package template

import (
	"os"
	"strings"
	"testing"

	"github.com/phlisg/frank-cli/internal/config"
)

// templatesDir points at the real templates directory relative to this test file.
const templatesDir = "../../templates"

func newTestEngine(t *testing.T) *Engine {
	t.Helper()
	fsys := os.DirFS(templatesDir)
	// Wrap in a sub-FS that mimics the "templates/" prefix the engine expects.
	// Since the engine prepends "templates/", we need to provide an FS rooted
	// one level above. Use os.DirFS at the frank-cli root instead.
	_ = fsys
	return New(os.DirFS("../.."))
}

func TestRenderRuntimeDockerfile_FrankenPHP(t *testing.T) {
	e := newTestEngine(t)
	out, err := e.RenderRuntime("frankenphp", "Dockerfile.tmpl", Data{PHPVersion: "8.4"})
	if err != nil {
		t.Fatalf("RenderRuntime error: %v", err)
	}
	if !strings.Contains(out, "dunglas/frankenphp:1-php8.4") {
		t.Errorf("expected PHP version in FROM line, got:\n%s", out)
	}
	if !strings.Contains(out, "# Generated by Frank") {
		t.Error("expected generated-by header")
	}
}

func TestRenderRuntimeDockerfile_FPM(t *testing.T) {
	e := newTestEngine(t)
	out, err := e.RenderRuntime("fpm", "Dockerfile.tmpl", Data{PHPVersion: "8.3"})
	if err != nil {
		t.Fatalf("RenderRuntime error: %v", err)
	}
	if !strings.Contains(out, "php:8.3-fpm") {
		t.Errorf("expected PHP version in FROM line, got:\n%s", out)
	}
}

func TestRenderRuntimeCaddyfile(t *testing.T) {
	e := newTestEngine(t)
	out, err := e.RenderRuntime("frankenphp", "Caddyfile.tmpl", Data{})
	if err != nil {
		t.Fatalf("RenderRuntime error: %v", err)
	}
	if !strings.Contains(out, ":80, :443") {
		t.Error("expected :80, :443 in Caddyfile")
	}
}

func TestRenderServiceCompose_PgsqlDefaults(t *testing.T) {
	e := newTestEngine(t)
	out, err := e.RenderServiceCompose("pgsql", config.ServiceConfig{}, "myapp")
	if err != nil {
		t.Fatalf("RenderServiceCompose error: %v", err)
	}
	if !strings.Contains(out, "postgres:latest") {
		t.Errorf("expected default postgres image, got:\n%s", out)
	}
	if !strings.Contains(out, "5432:5432") {
		t.Errorf("expected default pgsql port mapping, got:\n%s", out)
	}
}

func TestRenderServiceCompose_PgsqlOverride(t *testing.T) {
	e := newTestEngine(t)
	out, err := e.RenderServiceCompose("pgsql", config.ServiceConfig{Version: "16", Port: 5433}, "myapp")
	if err != nil {
		t.Fatalf("RenderServiceCompose error: %v", err)
	}
	if !strings.Contains(out, "postgres:16") {
		t.Errorf("expected overridden postgres version, got:\n%s", out)
	}
	if !strings.Contains(out, "5433:5432") {
		t.Errorf("expected overridden port, got:\n%s", out)
	}
}

func TestRenderServiceEnv_Pgsql(t *testing.T) {
	e := newTestEngine(t)
	out, err := e.RenderServiceEnv("pgsql", config.ServiceConfig{}, "my-project")
	if err != nil {
		t.Fatalf("RenderServiceEnv error: %v", err)
	}
	checks := []string{
		"DB_CONNECTION=pgsql",
		"DB_HOST=pgsql",
		"DB_PORT=5432",
		"DB_DATABASE=my-project",
		"DB_USERNAME=sail",
		"DB_PASSWORD=password",
	}
	for _, want := range checks {
		if !strings.Contains(out, want) {
			t.Errorf("expected %q in pgsql env, got:\n%s", want, out)
		}
	}
}

func TestRenderServiceEnv_Sqlite(t *testing.T) {
	e := newTestEngine(t)
	out, err := e.RenderServiceEnv("sqlite", config.ServiceConfig{}, "myapp")
	if err != nil {
		t.Fatalf("RenderServiceEnv error: %v", err)
	}
	if !strings.Contains(out, "DB_CONNECTION=sqlite") {
		t.Errorf("expected DB_CONNECTION=sqlite, got:\n%s", out)
	}
}

func TestRenderServiceCompose_Mailpit(t *testing.T) {
	e := newTestEngine(t)
	out, err := e.RenderServiceCompose("mailpit", config.ServiceConfig{}, "myapp")
	if err != nil {
		t.Fatalf("RenderServiceCompose error: %v", err)
	}
	if !strings.Contains(out, "1025:1025") {
		t.Errorf("expected SMTP port mapping, got:\n%s", out)
	}
	if !strings.Contains(out, "8025:8025") {
		t.Errorf("expected dashboard port mapping, got:\n%s", out)
	}
}

func TestRenderServiceEnv_Redis(t *testing.T) {
	e := newTestEngine(t)
	out, err := e.RenderServiceEnv("redis", config.ServiceConfig{}, "myapp")
	if err != nil {
		t.Fatalf("RenderServiceEnv error: %v", err)
	}
	if !strings.Contains(out, "REDIS_HOST=redis") {
		t.Errorf("expected REDIS_HOST, got:\n%s", out)
	}
	if !strings.Contains(out, "CACHE_STORE=redis") {
		t.Errorf("expected CACHE_STORE=redis, got:\n%s", out)
	}
}

func TestRenderMissingTemplate(t *testing.T) {
	e := newTestEngine(t)
	_, err := e.Render("templates/nonexistent.tmpl", Data{})
	if err == nil {
		t.Error("expected error for missing template")
	}
}

func TestAllServicesHaveEnvTemplate(t *testing.T) {
	e := newTestEngine(t)
	services := []string{"pgsql", "mysql", "mariadb", "sqlite", "redis", "memcached", "meilisearch", "mailpit"}
	for _, svc := range services {
		_, err := e.RenderServiceEnv(svc, config.ServiceConfig{}, "testapp")
		if err != nil {
			t.Errorf("service %q env template error: %v", svc, err)
		}
	}
}

func TestNonSqliteServicesHaveComposeFragment(t *testing.T) {
	e := newTestEngine(t)
	services := []string{"pgsql", "mysql", "mariadb", "redis", "memcached", "meilisearch", "mailpit"}
	for _, svc := range services {
		_, err := e.RenderServiceCompose(svc, config.ServiceConfig{}, "testapp")
		if err != nil {
			t.Errorf("service %q compose fragment error: %v", svc, err)
		}
	}
}
