package template

import (
	"os"
	"strings"
	"testing"

	"github.com/phlisg/frank/internal/config"
)

// templatesDir points at the real templates directory relative to this test file.
const templatesDir = "../../templates"

func newTestEngine(t *testing.T) *Engine {
	t.Helper()
	fsys := os.DirFS(templatesDir)
	// Wrap in a sub-FS that mimics the "templates/" prefix the engine expects.
	// Since the engine prepends "templates/", we need to provide an FS rooted
	// one level above. Use os.DirFS at the frank root instead.
	_ = fsys
	return New(os.DirFS("../.."))
}

func TestRenderRuntimeDockerfile_FrankenPHP(t *testing.T) {
	e := newTestEngine(t)
	out, err := e.RenderRuntime("frankenphp", "Dockerfile.tmpl", Data{PHPVersion: "8.4"})
	if err != nil {
		t.Fatalf("RenderRuntime error: %v", err)
	}
	checks := []string{
		"dunglas/frankenphp:1-php8.4",
		"AS builder",
		"AS final",
		"pecl install redis",
		"pecl install imagick",
		"pecl install memcached",
		"COPY --from=builder /usr/local/lib/php/extensions/",
		"COPY --from=builder /usr/local/etc/php/conf.d/",
		"strip --strip-all",
		"ARG WWWGROUP",
		"gosu sail",
		"/var/www/html",
		"# Generated by Frank",
	}
	for _, want := range checks {
		if !strings.Contains(out, want) {
			t.Errorf("expected %q in FrankenPHP Dockerfile, got:\n%s", want, out)
		}
	}
	if strings.Contains(out, `"/app`) {
		t.Error("old /app path must not appear; use /var/www/html throughout")
	}
}

func TestRenderRuntimeDockerfile_FPM(t *testing.T) {
	e := newTestEngine(t)
	out, err := e.RenderRuntime("fpm", "Dockerfile.tmpl", Data{PHPVersion: "8.3"})
	if err != nil {
		t.Fatalf("RenderRuntime error: %v", err)
	}
	// Uses PHPVersion "8.3" to stay independent of the golden fixture (which uses 8.4).
	// The template logic is the same for all supported versions.
	checks := []string{
		"ubuntu:24.04",
		"php8.3-fpm",
		"php8.3-redis",
		"php8.3-imagick",
		"php8.3-xdebug",
		"php8.3-memcached",
		"php8.3-mongodb",
		"ARG WWWGROUP",
		"gosu sail",
		"php-fpm8.3",
		"daemonize = no",
		"listen = 9000",
		"# Generated by Frank",
		"EXPOSE 9000",
	}
	for _, want := range checks {
		if !strings.Contains(out, want) {
			t.Errorf("expected %q in FPM Dockerfile, got:\n%s", want, out)
		}
	}
	if strings.Contains(out, "php:8.3-fpm") {
		t.Error("old php:8.3-fpm base image must be removed")
	}
	if strings.Contains(out, ".sock") {
		t.Error("FPM must not use a Unix socket; expected TCP 9000")
	}
}

func TestRenderRuntimeCaddyfile(t *testing.T) {
	e := newTestEngine(t)
	out, err := e.RenderRuntime("frankenphp", "Caddyfile.tmpl", Data{})
	if err != nil {
		t.Fatalf("RenderRuntime error: %v", err)
	}
	if !strings.Contains(out, ":80, :443") {
		t.Error("expected :80, :443 in Caddyfile")
	}
}

func TestRenderServiceCompose_PgsqlDefaults(t *testing.T) {
	e := newTestEngine(t)
	out, err := e.RenderServiceCompose("pgsql", config.ServiceConfig{}, "myapp")
	if err != nil {
		t.Fatalf("RenderServiceCompose error: %v", err)
	}
	if !strings.Contains(out, "postgres:latest") {
		t.Errorf("expected default postgres image, got:\n%s", out)
	}
	if !strings.Contains(out, "5432:5432") {
		t.Errorf("expected default pgsql port mapping, got:\n%s", out)
	}
}

func TestRenderServiceCompose_PgsqlOverride(t *testing.T) {
	e := newTestEngine(t)
	out, err := e.RenderServiceCompose("pgsql", config.ServiceConfig{Version: "16", Port: 5433}, "myapp")
	if err != nil {
		t.Fatalf("RenderServiceCompose error: %v", err)
	}
	if !strings.Contains(out, "postgres:16") {
		t.Errorf("expected overridden postgres version, got:\n%s", out)
	}
	if !strings.Contains(out, "5433:5432") {
		t.Errorf("expected overridden port, got:\n%s", out)
	}
}

func TestRenderServiceEnv_Pgsql(t *testing.T) {
	e := newTestEngine(t)
	out, err := e.RenderServiceEnv("pgsql", config.ServiceConfig{}, "my-project")
	if err != nil {
		t.Fatalf("RenderServiceEnv error: %v", err)
	}
	checks := []string{
		"DB_CONNECTION=pgsql",
		"DB_HOST=pgsql",
		"DB_PORT=5432",
		"DB_DATABASE=my-project",
		"DB_USERNAME=sail",
		"DB_PASSWORD=password",
	}
	for _, want := range checks {
		if !strings.Contains(out, want) {
			t.Errorf("expected %q in pgsql env, got:\n%s", want, out)
		}
	}
}

func TestRenderServiceEnv_Sqlite(t *testing.T) {
	e := newTestEngine(t)
	out, err := e.RenderServiceEnv("sqlite", config.ServiceConfig{}, "myapp")
	if err != nil {
		t.Fatalf("RenderServiceEnv error: %v", err)
	}
	if !strings.Contains(out, "DB_CONNECTION=sqlite") {
		t.Errorf("expected DB_CONNECTION=sqlite, got:\n%s", out)
	}
}

func TestRenderServiceCompose_Mailpit(t *testing.T) {
	e := newTestEngine(t)
	out, err := e.RenderServiceCompose("mailpit", config.ServiceConfig{}, "myapp")
	if err != nil {
		t.Fatalf("RenderServiceCompose error: %v", err)
	}
	if !strings.Contains(out, "1025:1025") {
		t.Errorf("expected SMTP port mapping, got:\n%s", out)
	}
	if !strings.Contains(out, "8025:8025") {
		t.Errorf("expected dashboard port mapping, got:\n%s", out)
	}
}

func TestRenderServiceEnv_Redis(t *testing.T) {
	e := newTestEngine(t)
	out, err := e.RenderServiceEnv("redis", config.ServiceConfig{}, "myapp")
	if err != nil {
		t.Fatalf("RenderServiceEnv error: %v", err)
	}
	if !strings.Contains(out, "REDIS_HOST=redis") {
		t.Errorf("expected REDIS_HOST, got:\n%s", out)
	}
	if !strings.Contains(out, "CACHE_STORE=redis") {
		t.Errorf("expected CACHE_STORE=redis, got:\n%s", out)
	}
}

func TestRenderMissingTemplate(t *testing.T) {
	e := newTestEngine(t)
	_, err := e.Render("templates/nonexistent.tmpl", Data{})
	if err == nil {
		t.Error("expected error for missing template")
	}
}

func TestAllServicesHaveEnvTemplate(t *testing.T) {
	e := newTestEngine(t)
	services := []string{"pgsql", "mysql", "mariadb", "sqlite", "redis", "memcached", "meilisearch", "mailpit"}
	for _, svc := range services {
		_, err := e.RenderServiceEnv(svc, config.ServiceConfig{}, "testapp")
		if err != nil {
			t.Errorf("service %q env template error: %v", svc, err)
		}
	}
}

func TestNonSqliteServicesHaveComposeFragment(t *testing.T) {
	e := newTestEngine(t)
	services := []string{"pgsql", "mysql", "mariadb", "redis", "memcached", "meilisearch", "mailpit"}
	for _, svc := range services {
		_, err := e.RenderServiceCompose(svc, config.ServiceConfig{}, "testapp")
		if err != nil {
			t.Errorf("service %q compose fragment error: %v", svc, err)
		}
	}
}

func TestRenderRuntimeCompose_FPM_SailUser(t *testing.T) {
	e := newTestEngine(t)
	out, err := e.RenderRuntime("fpm", "compose.fragment.tmpl", Data{PHPVersion: "8.4"})
	if err != nil {
		t.Fatalf("RenderRuntime error: %v", err)
	}
	if !strings.Contains(out, "WWWGROUP") {
		t.Error("expected WWWGROUP build arg in fpm compose fragment")
	}
	if !strings.Contains(out, "WWWUSER") {
		t.Error("expected WWWUSER env var in fpm compose fragment")
	}
	if strings.Contains(out, "user: ") {
		t.Error("fpm compose fragment must not contain user: directive (gosu handles it)")
	}
}

func TestRenderRuntimeCompose_FrankenPHP_SailUser(t *testing.T) {
	e := newTestEngine(t)
	out, err := e.RenderRuntime("frankenphp", "compose.fragment.tmpl", Data{PHPVersion: "8.4"})
	if err != nil {
		t.Fatalf("RenderRuntime error: %v", err)
	}
	if !strings.Contains(out, "WWWGROUP") {
		t.Error("expected WWWGROUP build arg in frankenphp compose fragment")
	}
	if !strings.Contains(out, "WWWUSER") {
		t.Error("expected WWWUSER env var in frankenphp compose fragment")
	}
	if strings.Contains(out, "user: ") {
		t.Error("frankenphp compose fragment must not contain user: directive (gosu handles it)")
	}
}
